/*
 * AggieCatalog.jsx
 *
 * One source of truth: every component family in AggieUX 1.7, grouped.
 * Each entry: { id, label, page, figma, styles, darkMode, status, blurb }
 *
 *   id       — slug used for routing + DOM ids
 *   page     — section group (Components, Navigation, Specialized, Templates, Icons, Foundations)
 *   figma    — VFS path in the mounted Figma file (for our own reference)
 *   styles   — which of (default, bold, elegant) the family supports
 *   darkMode — whether the family has an On Dark=True variant
 *   status   — 'scaffold' | 'in-progress' | 'ready'
 *   blurb    — one line describing what this component does
 *
 * Every page has a placeholder until we start filling in component variants.
 */

window.AGGIE_CATALOG = [

  /* ─── Foundations (new, not in Figma 1.7 — carried from tux) ───── */
  { id: "intro",           label: "Overview",          page: "Foundations", figma: "/Get-Started-Changelog", styles: [], darkMode: false, status: "ready",
    blurb: "What this kit is, how it relates to tux, what's here and what's next." },
  { id: "style-variants",  label: "Style variants",    page: "Foundations", figma: null, styles: ["default","bold","elegant"], darkMode: false, status: "ready",
    blurb: "The three section styles applied across common patterns. Reference for how each variant's signature (underline vs bar vs hash) plays out." },
  { id: "visual-language", label: "Visual language",   page: "Foundations", figma: null, styles: [], darkMode: true, status: "ready",
    blurb: "Token-level finishing details refreshed in the Batch E-prelude — two-ring focus, transportation-tempo easings, four-tier elevation, warm-neutral ramp, survey rhythm, identity primitives. Lineage notes for each." },

  /* ─── Navigation — site-level chrome ────────────────────────────── */
  { id: "identities",      label: "Identities",        page: "Navigation",  figma: "/Navigation/Identities",        styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Lockup identity (logo + institution wordmark) and text identity (institution name as typography). Four navigation options pair with these." },
  { id: "menus",           label: "Menus",             page: "Navigation",  figma: "/Navigation/Menus",             styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Sidebar menu, in-page nav, dropdown (v2.0), and mega menu (v2.0). Pair with lockup or text identity for four navigation combinations. Lineage: Microsoft Teams Secondary-left-navigation (sidebar menu anatomy)." },
  { id: "navigation",      label: "Site navigation",   page: "Navigation",  figma: "/Navigation/Navigation",        styles: ["default"], darkMode: true,  status: "ready",
    blurb: "The site header: utility nav (upper strip) + identity nav (main bar). Five site types \u2014 University, Center, Department, Application w/ nav, Application only. Each in light + dark." },
  { id: "breadcrumbs",     label: "Breadcrumbs",       page: "Navigation",  figma: "/Navigation/Breadcrumbs",       styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Home icon + pipe-separated trail. Italic Work Sans on intermediate crumbs. Four page-depth variants — Landing, L2, L3, Article. Lineage: Microsoft Teams Breadcrumb." },
  { id: "search",          label: "Search",            page: "Navigation",  figma: "/Navigation/Search",            styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Bordered inline search bar with attached uppercase SEARCH button. Regular (60px) and slim (51px) sizes, plus focus state." },
  { id: "search-block",    label: "Search block",      page: "Navigation",  figma: "/Navigation/Search-Block",      styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Labeled search unit — heading + bar + optional lede. For footers, sidebars, dedicated search pages." },
  { id: "footers",         label: "Footers",           page: "Navigation",  figma: "/Navigation/Footers",           styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Main footer block (logo column + 3 or 4 link columns + optional newsletter) plus compliance strip. Application-footer variant for internal tools." },
  { id: "subfooter",       label: "Subfooter",         page: "Navigation",  figma: "/Navigation/Subfooter",         styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Mandatory TAMUS legal strip. Non-negotiable for every TTI site. Contains lockup, Coordinated Statewide Transportation Research Program tagline, state-agency links, © line." },

  /* ─── Components — editorial body patterns ─────────────────────── */
  { id: "page-headers",        label: "Page headers",            page: "Components", figma: "/Components/Page-Headers",                  styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Top-of-page hero w/ superhead, title, subhead, optional CTA. The signature slot for each style variant. Lineage: SharePoint Page-title Overlap + Hero Layers." },
  { id: "standard-page-header", label: "Standard page header",   page: "Components", figma: "/Components/Standard-Page-Header",          styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Standard editorial page header — title + eyebrow + lede. Variations 1/2/3 differ in compositional rhythm. Lineage: SharePoint Page-title Color-block / Image-and-title / Plain." },
  { id: "card-groups",         label: "Card groups",             page: "Components", figma: "/Components/Card-Groups",                   styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Grid of standard cards. 2/3/4-up, with or without images, linked or static. Lineage: SharePoint Highlighted-Content Grid." },
  { id: "card-groups-featured", label: "Card groups w/ featured", page: "Components", figma: "/Components/Card-Groups-with-Featured-Cards", styles: ["default","bold","elegant"], darkMode: true, status: "ready", blurb: "Card group with one oversized hero card + supporting cards at standard size. Lineage: SharePoint Highlighted-Content Filmstrip + News-Top-story." },
  { id: "standard-card-featured", label: "Standard card + featured", page: "Components", figma: "/Components/Standard-Card-Group-with-Standard-Featured-Card", styles: ["default","bold","elegant"], darkMode: true, status: "ready", blurb: "Featured-card layout that keeps the hero at the same dimensions as its siblings — just marked with a visual flag." },
  { id: "card-slab",           label: "Card slab",               page: "Components", figma: "/Components/Card-Slab",                     styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Full-bleed edge-to-edge card band. Media-forward, oversized title. Lineage: SharePoint Hero Tiles." },
  { id: "cta-feature",         label: "CTA feature",             page: "Components", figma: "/Components/CTA-Feature",                   styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Large promotional block with headline + body + primary/secondary CTA. The loudest editorial surface short of a page header." },
  { id: "cta-links",           label: "CTA links",               page: "Components", figma: "/Components/CTA-Links",                     styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Group of prominent text links with icon + description. Quick routing from a hub page." },
  { id: "callouts",            label: "Callouts",                page: "Components", figma: "/Components/Callouts",                      styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Pulled-aside editorial callout — highlight a stat, a fact, or a quote inline with body flow." },
  { id: "standalone-blockquote", label: "Standalone blockquote", page: "Components", figma: "/Components/Standalone-Blockquote",         styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Full-width featured pullquote with attribution. Italic display face, oversized quote mark." },
  { id: "testimonials",        label: "Testimonial collection",  page: "Components", figma: "/Components/Testimonial-Collection",        styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Grid or carousel of attributed testimonials with photo, quote, name, role." },
  { id: "factoids",            label: "Factoid collections",     page: "Components", figma: "/Components/Factoid-Collections",           styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Row of oversized statistics — the institutional \"by the numbers\" treatment. 3/4/5-up." },
  { id: "split-feature",       label: "Split feature",           page: "Components", figma: "/Components/Split-Feature",                 styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Two-column feature with image on one side and copy + CTA on the other. Alternates left/right." },
  { id: "media-features",      label: "Media features",          page: "Components", figma: "/Components/Media-Features",                styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Full-bleed media-forward block with overlaid or adjacent copy." },
  { id: "media-slab",          label: "Media slab",              page: "Components", figma: "/Components/Media-Slab",                    styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Edge-to-edge media band — hero image + minimal copy. The \"big photo\" moment." },
  { id: "captioned-media",     label: "Captioned media",         page: "Components", figma: "/Components/Captioned-Media",               styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Inline media asset with caption + credit. Supports 16:9, 1:1, 4:3." },
  { id: "video-embed",         label: "Video embed",             page: "Components", figma: "/Components/Video-Embed",                   styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Responsive video player wrapper — YouTube, Vimeo, or self-hosted." },
  { id: "embed",               label: "Embed",                   page: "Components", figma: "/Components/Embed",                         styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Generic iframe container for third-party content with a branded border treatment." },
  { id: "photo-grid",          label: "Photo grid",              page: "Components", figma: "/Components/Photo-Grid",                    styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Masonry/uniform grid of photographs. Optional caption row." },
  { id: "logo-grid",           label: "Logo grid",               page: "Components", figma: "/Components/Logo-Grid",                     styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Partner / sponsor / agency logo wall. Grayscale/color variants." },
  { id: "news-collection",     label: "News collection",         page: "Components", figma: "/Components/News-Collection",               styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "List of news articles with date, dek, thumbnail. Paginated. Lineage: SharePoint News (Hub / List / Side-by-side / Top-story / Tiles / Carousel)." },
  { id: "contact-cards",       label: "Contact card collection", page: "Components", figma: "/Components/Contact-Card-Collections",      styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Faculty/staff directory card group — photo, name, title, contact links. Lineage: SharePoint People." },
  { id: "contact-cards-b",     label: "Contact card coll. (B)",  page: "Components", figma: "/Components/Contact-Card-Collection-Option-B", styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Alternate contact card layout — horizontal, inline with copy." },
  { id: "collection-feature",  label: "Collection feature",      page: "Components", figma: "/Components/Collection-Feature",            styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Featured group from a larger collection — e.g. \"three recent publications\" pulled onto a landing page. Lineage: SharePoint Highlighted-Content Compact." },
  { id: "icon-feature",        label: "Icon feature collection", page: "Components", figma: "/Components/Icon-Feature-Collection",       styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Grid of icon + headline + body — the classic \"our services\" block. Lineage: SharePoint Quick-Links Grid." },
  { id: "icon-list",           label: "Icon list collections",   page: "Components", figma: "/Components/Icon-List-Collections",         styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "List of items each prefixed by an icon. More compact than icon-feature. Lineage: SharePoint Quick-Links Compact." },
  { id: "link-list",           label: "Link list collections",   page: "Components", figma: "/Components/Link-List-Collections",         styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Resource list — arrows/caret rows, grouped and titled. Lineage: SharePoint Quick-Links Compact/List." },
  { id: "link-slab",           label: "Link slab",               page: "Components", figma: "/Components/Link-Slab",                     styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Full-width horizontal band of links — footer-of-section navigation. Lineage: SharePoint Quick-Links Button/Filmstrip." },
  { id: "button-slab",         label: "Button slab",             page: "Components", figma: "/Components/Button-Slab",                   styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Band of CTA buttons on a branded background." },
  { id: "accordion-groups",    label: "Accordion groups",        page: "Components", figma: "/Components/Accordion-Groups",              styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Expand/collapse FAQ groups with accessible disclosure patterns." },
  { id: "publication-accordion", label: "Publication accordion", page: "Components", figma: "/Components/Publication-Accordion-Groups",  styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Accordion tuned for publications — author, year, citation, abstract inside." },
  { id: "qa-collections",      label: "Q&A collections",         page: "Components", figma: "/Components/Q-A-Collections",               styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Q&A editorial pattern — question prompt above long-form answer." },
  { id: "description-list",    label: "Description list",        page: "Components", figma: "/Components/Description-List-Collection",   styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Term/description pairs — event details, spec tables, metadata blocks." },
  { id: "tables",              label: "Tables",                  page: "Components", figma: "/Components/Tables",                        styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Editorial data tables with caption, th-scoped headers, optional zebra striping." },
  { id: "alerts",              label: "Alerts",                  page: "Components", figma: "/Components/Alerts",                        styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Page-level status banner — info, warning, error, success. Dismissible variant + a Base-anatomy compact / utility variant (soft tinted card, no rule, with Low / High hierarchy) for dashboard rows and inline form responses. Lineage: Microsoft Teams Notification-bar (editorial variants) + Base Gallery Banner (utility variant)." },
  { id: "buttons",             label: "Buttons",                 page: "Components", figma: "/Components/Buttons",                       styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Primary, secondary, tertiary, icon-only. Sizes: default / small. Width: auto / full. Hover + focus states." },
  { id: "sidebar-components",  label: "Sidebar components",      page: "Components", figma: "/Components/Sidebar-Components",            styles: ["default","bold","elegant"], darkMode: true,  status: "ready"   , blurb: "In-page sidebar blocks — related links, contact box, in-page nav, quick facts." },
  { id: "signup-feature",      label: "Sign-up feature",         page: "Components", figma: "/Components/Sign-Up-Feature",               styles: ["default","bold","elegant"], darkMode: true,  status: "ready"   , blurb: "Newsletter / mailing list sign-up block with email input + consent line." },
  { id: "social-banner",       label: "Social media banner",     page: "Components", figma: "/Components/Social-Media-Banner",           styles: ["default","bold","elegant"], darkMode: true,  status: "ready"   , blurb: "Footer-adjacent follow-us strip — icons + handles per platform." },
  { id: "custom-content",      label: "Custom content",          page: "Components", figma: "/Components/Custom-Content",                styles: ["default","bold","elegant"], darkMode: true,  status: "ready"   , blurb: "Escape hatch — a styled container for bespoke layouts that don't fit any other family." },

  /* ─── Status states — empty / error / loading / progress ──────── */
  { id: "empty-state",         label: "Empty states",            page: "Status",     figma: null, styles: ["default","bold","elegant"], darkMode: true,  status: "ready",
    blurb: "First-run · search-empty · list-empty. Editorial empty panels with a geometric mark, signature rule, eyebrow, title, body, recovery action. Never cartoony. Guardrail (Base sanity baseline): for transient post-action success/failure feedback prefer `toast`; for persistent surface-level prefer `alerts`; empty-state is for when the data slot itself is unavailable. Lineage: Base Gallery Empty-state (state-class taxonomy)." },
  { id: "error-page",          label: "Error pages",             page: "Status",     figma: null, styles: ["default","bold","elegant"], darkMode: false, status: "ready",
    blurb: "404 · 410 · 403 · 500 full-page templates. Big code mark, signature rule, recovery actions. 500-class includes a system-status line." },
  { id: "skeleton-loader",     label: "Skeleton loaders",        page: "Status",     figma: null, styles: ["default"], darkMode: false, status: "ready",
    blurb: "Shimmer placeholders for cards, list rows, tables, and article body. Neutral surface only — never branded. Honors prefers-reduced-motion." },
  { id: "stepper",             label: "Stepper",                 page: "Status",     figma: null, styles: ["default"], darkMode: false, status: "ready",
    blurb: "Numbered-circle multi-step indicator. Three states: complete · current · upcoming. Horizontal (top of form) + vertical (sidebar with descriptions)." },

  /* ─── Guidance & onboarding (Batch D) ──────────────────────────── */
  { id: "teaching-banner",     label: "Teaching banner",         page: "Status",     figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Inline coachmark — feature reveals, workflow tips, system advisories. Three tones (info / advisory / spotlight) and three sizes (compact / standard / hero). Lineage: Microsoft Fabric Teaching-banner." },
  { id: "teaching-popover",    label: "Teaching popover",        page: "Status",     figma: null, styles: ["default"], darkMode: false, status: "ready",
    blurb: "Anchored callout for product tours. Step counter, dot progress, skip / prev / next / done actions. Maroon body, gold accents. Lineage: Microsoft Fluent 2 Web Teaching-popover (anatomy) + Fabric pattern (variant naming)." },
  { id: "wizard",              label: "Wizard",                  page: "Status",     figma: null, styles: ["default"], darkMode: false, status: "ready",
    blurb: "Multi-step linear flow. Numbered / named / progress-bar headers, horizontal + vertical steppers. Footer pairs Skip with Previous + Continue/Finish. Lineage: Microsoft Fabric Wizard." },

  /* ─── INF-1 new TUX components (from Fluent 2 Web gap analysis) ── */
  { id: "toast",               label: "Toast",                   page: "Overlays",   figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Transient status notification with optional inline progress + quick actions. Four tones (info / success / warning / error), stacks in a corner region, auto-dismisses with hover-pause. Lineage: Microsoft Fluent 2 Web Toast." },
  { id: "spinner",             label: "Spinner",                 page: "Status",     figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Circular indeterminate loading indicator for short waits and inline status. Five sizes (xs / sm / md / lg / xl), three tones (brand / neutral / inverse), three label placements (after / before / below). Pairs with skeleton-loader; reach for spinner for ambient activity. Lineage: Microsoft Fluent 2 Web Spinner." },
  { id: "progress-bar",        label: "Progress bar",            page: "Status",     figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Linear progress for tasks with a known duration or a stream of work. Determinate (animated fill) and indeterminate (gradient-mask traveling segment). Three heights (2 / 4 / 6px) and four status tones. Lineage: Microsoft Fluent 2 Web Progress-bar." },
  { id: "switch",              label: "Switch",                  page: "Components", figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Binary toggle for settings and feature flags — takes effect immediately on click. Two sizes (sm 32×16 for data tables / md 40×20 default), label-before and label-after layouts. Distinct from checkbox (intent confirmed later) and radio (one of N). Lineage: Microsoft Fluent 2 Web Switch." },
  { id: "slider",              label: "Slider",                  page: "Components", figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Continuous range input for filters, thresholds, and confidence tuning. Single-thumb selects a value; range selects an interval. Optional ticks turn it into a discrete step picker. Keyboard nav with arrows / Home / End. Lineage: Microsoft Fluent 2 Web Slider." },

  /* ─── INF-3 new TUX components (from Teams gap analysis) ────────── */
  { id: "adaptive-card",       label: "Adaptive card",           page: "Components", figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Structured response card for AI agents and tool output. Composes from five slots: source header (sender + timestamp + menu), title, body, attachments, action row. Five tones (default / info / success / warning / error). For tti-ai-studio conversational surfaces and inline tool results. Lineage: Microsoft Teams Adaptive Cards." },
  { id: "metric-tile",         label: "Metric tile",             page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Single-statistic dashboard tile — title + 1–3 data points + optional trend delta + drill-in CTA. Grid-friendly at 296px. Distinct from factoids (hero marketing numbers) and stat-comparison (side-by-side). For PECAN-class operational dashboards. Lineage: Microsoft Teams Data-viz Number chart." },

  /* ─── INF-3b deferred fold (Fluent 2 Web + Teams Toolbar + Teams Lightbox-view) ── */
  { id: "toolbar",             label: "Toolbar",                 page: "Components", figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Horizontal action surface above a content region — corridor view, record editor, data grid. Composes from icon-only / mixed icon+text / toggle / split buttons, dividers, and an overflow menu. Three densities (sm 32 / md 40 / lg 48) for table-row, default, and decklike surfaces. Distinct from buttons (free-floating atoms) and horizontal-filters (filter-strip). Lineage: Microsoft Fluent 2 Web Toolbar + Teams Toolbar." },
  { id: "image-lightbox",      label: "Image lightbox",          page: "Overlays",   figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "Full-viewport modal for previewing photography and document imagery — the focused-view pair to photo-grid. Chrome bar (title + meta + close), image stage with prev/next, counter + zoom strip, plus an opt-in tail: caption + attribution, filmstrip of siblings, or numbered annotation pins. Distinct from captioned-media (inline body) and video-embed (inline player). Lineage: Microsoft Teams Lightbox-view." },

  /* ─── INF-4.5b new TUX components (Bootstrap 5 DS gap fold) ──────── */
  { id: "transfer",            label: "Transfer",                page: "Components", figma: null, styles: ["default"], darkMode: false, status: "ready",
    blurb: "Dual-list selector for 'select N from a large catalog' research flows — corridor pickers, faculty co-author selection, dataset attribute pickers. Two paired panes (left = available, right = selected) with per-pane search + tri-state select-all + a 4-arrow column (all-right · checked-right · checked-left · all-left). Distinct from dropdown-rich (small fixed list with chips) and combobox (single-select autocomplete). Lineage: Bootstrap 5 Design System Transfer." },
  { id: "rate",                label: "Rate",                    page: "Components", figma: null, styles: ["default"], darkMode: true,  status: "ready",
    blurb: "N-icon rating for surveys, publication scoring, and reviewer panels. Half-step precision (default) or full-step. Display-only and interactive modes. Custom-icon variants (heart, flag) for non-star vocabularies. Item counts 3 / 4 / 5; sizes sm 16 / md 22 / lg 28. Brand maroon filled, gold on dark. Distinct from slider (continuous range) and stat-comparison (display-only stat). Lineage: Bootstrap 5 Design System Rate." },

  /* ─── Specialized — narrower patterns ─────────────────────────── */
  { id: "specialized-page-headers", label: "Specialized page headers", page: "Specialized", figma: "/Specialized/Specialized-Page-Headers", styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Page headers tuned for specific contexts — news article, event, faculty profile, publication." },
  { id: "news-story-footer",   label: "News story footer",       page: "Specialized", figma: "/Specialized/News-Story-Footer",             styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "End-of-article block — author, tags, share, next article suggestions." },
  { id: "pagination",          label: "Pagination",              page: "Specialized", figma: "/Specialized/Pagination",                    styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Page 1 of N controls — prev/next + numbered pages + page size." },
  { id: "horizontal-filters",  label: "Horizontal filters",      page: "Specialized", figma: "/Specialized/Horizontal-Filters",            styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Top-of-list filter bar — dropdowns, toggles, clear-all, result count. Lineage: Microsoft Teams Filter-Sort." },
  { id: "sidebar-filtration",  label: "Sidebar filtration",      page: "Specialized", figma: "/Specialized/Sidebar-Filtration",            styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Left-rail facet filtering — grouped checkboxes, collapsible sections, applied-filter chips." },
  { id: "alpha-nav",           label: "Alpha nav",               page: "Specialized", figma: "/Specialized/Alpha-Nav",                     styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "A–Z jump-nav — glossaries, directories, index pages." },
  { id: "directory",           label: "Directory",               page: "Specialized", figma: "/Specialized/Directory",                     styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Faculty/staff directory layout — search + filters + contact-card list." },
  { id: "glossary",            label: "Glossary",                page: "Specialized", figma: "/Specialized/Glossary",                      styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Term/definition pairs, A-Z grouped, with alpha-nav jump bar." },
  { id: "calendar-event",      label: "Calendar / event widgets", page: "Specialized", figma: "/Specialized/Calendar-Event-Widgets",       styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Event card, month calendar, upcoming-events list, agenda view. Batch-H refit adds a range-selector header and a richer event-detail popover." },
  { id: "date-range-picker",   label: "Date range picker",       page: "Specialized", figma: null,                                          styles: ["default"], darkMode: false, status: "ready", blurb: "Date-range selection for reports, exports, and filters. Dual / single / inline variants with a preset bar (today, 7d, 30d, MTD, QTD, FY). Lineage: MUI X Date Range Picker, Material 3 Date Picker." },
  { id: "inline-feed-group",   label: "Inline feed group",       page: "Specialized", figma: "/Specialized/Inline-Feed-Group",             styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Embeddable social/news feed block — pulls from an RSS or API source. Lineage: Microsoft Teams Activity-feed-notifications." },
  { id: "example-forms",       label: "Example forms",           page: "Specialized", figma: "/Specialized/Example-Forms",                 styles: ["default","bold","elegant"], darkMode: true, status: "ready"   , blurb: "Form layouts for common flows — contact, registration, RFP, search. Shows label + help + error patterns." },
  { id: "code-maroon-banner",  label: "Code Maroon banner",      page: "Specialized", figma: "/Specialized/Code-Maroon-Banner",            styles: ["default"], darkMode: false, status: "ready"   , blurb: "TAMU-wide emergency alert banner. Fixed styling — this is system-wide safety messaging and doesn't style-switch." },

  /* ─── Overlays — global app chrome above content ──────────────── */
  { id: "command-palette",     label: "Command palette",         page: "Overlays",  figma: null,                                   styles: ["default"], darkMode: true,  status: "ready"   , blurb: "Global ⌘K jump bar. Native <dialog> scrim, grouped commands w/ live filter, keyboard navigation, action or navigation per command. Single instance at app root." },
  { id: "modal",               label: "Modal",                   page: "Overlays",  figma: null,                                   styles: ["default","bold","elegant"], darkMode: false, status: "ready"   , blurb: "Editorial modal — eyebrow + signature-rule title, body, footer actions. Wraps a primitive (UModal in Vue) with TTI editorial rhythm. Confirm-before-destroy variant included. Lineage: Microsoft Teams Task-modules + Stage-view." },
  { id: "toc",                 label: "Table of contents",       page: "Overlays",  figma: null,                                   styles: ["default","bold","elegant"], darkMode: true,  status: "ready"   , blurb: "Right-rail sticky TOC for long-form articles. H2/H3 hierarchy, active-section tracking, keyboard navigable. Pairs with TuxDocsSidebar on doc pages." },
  { id: "announcement-banner", label: "Announcement banner",     page: "Overlays",  figma: null,                                   styles: ["default","bold","elegant"], darkMode: true,  status: "ready"   , blurb: "Top-of-page institutional banner — research milestones, deadlines, system advisories. Three tones (info / advisory / urgent). Dismissible per-session. Sits above the site header." },
  { id: "cookie-consent",      label: "Cookie consent",          page: "Overlays",  figma: null,                                   styles: ["default"], darkMode: false, status: "ready"   , blurb: "Bottom-anchored consent strip. TAMUS-flavored copy referencing the Texas privacy framework. Accept-all / essential-only / customize. Customize opens a category panel with toggles per cookie group." },
  { id: "beta-ribbon",         label: "Beta ribbon",             page: "Overlays",  figma: null,                                   styles: ["default"], darkMode: false, status: "ready"   , blurb: "Pre-release flag for internal/research apps — corner ribbon variant + inline banner variant + stacked-with-feedback variant. Calls out beta / alpha / preview state and links to a feedback channel." },
  { id: "badge-chip-tag",      label: "Badges, chips, tags",     page: "Components", figma: null,                                  styles: ["default"], darkMode: true,  status: "ready"   , blurb: "Inline status atoms. Badges (numeric + dot indicators on icons/avatars), chips (interactive — filter, removable, choice), tags (semantic — tone-coded labels for content metadata). Sizes sm/md, four tones." },
  { id: "form-text",           label: "Text inputs",             page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Text · email · password · search · textarea · number · phone. Sizes sm/md, with leading/trailing icons, prefix/suffix slots, helper text, character counter, masked input. Includes a dense (32px) density variant from the Batch G refit." },
  { id: "form-select",         label: "Select & combobox",       page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Native select · custom listbox · multi-select with chips · combobox with autocomplete and grouped results. Async-loading state included. Dense (32px) density variant from the Batch G refit." },
  { id: "form-choice",         label: "Choice — radio & checkbox", page: "Components", figma: null,                                styles: ["default"], darkMode: false, status: "ready"   , blurb: "Single-select radio groups · multi-select checkbox groups · stacked card-style choices · indeterminate parent + nested children. All sizes meet 44px hit targets." },
  { id: "form-date",           label: "Date & time",             page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Date input · date range · single-month and dual-month calendars · time picker. Locale-aware formatting; inline-error patterns covered." },
  { id: "form-file",           label: "File upload",             page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Single-file picker · drop-zone with preview · multi-file list with progress bars and per-row actions. Mime-type and size restrictions are visible upfront." },
  { id: "dropdown-rich",       label: "Dropdown · rich",         page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Multiselect with search, grouped options, tag chips, select-all / clear-all, and a +N overflow chip. For long, grouped lists where ≤20 radios would be cramped. Lineage: Ant Select + Fabric Dropdown." },
  { id: "combobox",            label: "Combobox · autocomplete", page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Single-select autocomplete with strict, async, and free-text modes. Keyboard nav, inline validation, project-lookup demo. Lineage: Ant AutoComplete + Fabric Combobox." },
  { id: "field-grid",          label: "Field grid · density",    page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Multi-column form layout with three density tiers (comfortable / standard / compact) mapped to survey-rhythm tokens. Label-above and label-left variants. Lineage: Ant Form labelCol + Microsoft Fluent 2 Web Field + Fabric Field." },
  { id: "inline-validation",   label: "Inline validation",       page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Field-level error / success / warning patterns. Help text vs error text rules, server-side error display, async validation spinner, password-strength meter." },
  { id: "tooltip-popover",     label: "Tooltip & popover",       page: "Overlays",   figma: null,                                  styles: ["default"], darkMode: true,  status: "ready"   , blurb: "Anchored disclosures. Tooltip is single-line transient hint (icon button label, disabled-button reason, abbreviation); popover is rich, focus-trapping content (term definition, hover card)." },
  { id: "load-more",           label: "Load more & paging",      page: "Specialized", figma: null,                                 styles: ["default"], darkMode: false, status: "ready"   , blurb: "Result-count strip · explicit load-more button (idle / loading / done) · sentinel-driven infinite scroll. Decision matrix for which pattern fits which list shape." },
  { id: "comment-thread",      label: "Comments & reactions",    page: "Components", figma: null,                                  styles: ["default"], darkMode: false, status: "ready"   , blurb: "Editorial review atoms — anchored comment threads with open/resolved status, threaded replies, marginal indicator; curated 6-glyph reaction vocabulary with picker." },

  /* ─── Data viz — charts and stat displays ─────────────────────────── */
  { id: "chart-foundations",   label: "Chart foundations",       page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Categorical palette, axis system, type ramp, and signature rule for charts. The shared anatomy every other chart inherits." },
  { id: "chart-bar",           label: "Bar charts",              page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Vertical · horizontal · grouped · stacked. Mode-share splits, mileage by district, before-and-after comparisons." },
  { id: "chart-line",          label: "Line charts",             page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Single series · multi-series · area variant. Time-of-day delay curves, daily counts, multi-corridor comparison over time." },
  { id: "chart-scatter",       label: "Scatter & bubble",        page: "Data viz",   figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "X/Y plots for correlation studies. Bubble variant adds a third encoded dimension. Quadrant overlays for strategy frameworks." },
  { id: "chart-trend",         label: "Trend strips",            page: "Data viz",   figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Inline sparklines and KPI trend strips. Sit beside a metric. Show direction without distracting from the headline number." },
  { id: "stat-comparison",     label: "Stat comparison",         page: "Data viz",   figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Side-by-side and before/after stat blocks. Hero stat. Bigger numerals than chart axis labels." },

  { id: "chart-treatments",    label: "Treatment system",        page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "How any chart adapts across four delivery contexts: standard, on-dark for slide decks, print-ready for grayscale PDF, and formal exhibit caption with DOI/CC citation." },
  { id: "chart-hierarchy",     label: "Treemap & sunburst",      page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Hierarchical part-to-whole. Treemap for budget breakdowns; sunburst for radial program structures." },
  { id: "chart-waterfall",     label: "Waterfall",               page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Contribution analysis — how a starting value becomes an ending value through positive and negative steps." },
  { id: "chart-radar",         label: "Radar / spider",          page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Multi-criteria scoring. For project evaluation matrices and capability comparisons." },
  { id: "chart-change",        label: "Slope · dumbbell · lollipop", page: "Data viz", figma: null, styles: ["default"], darkMode: true, status: "ready", blurb: "Three lightweight charts for change in ranked lists. Slope shows movement; dumbbell shows gap; lollipop shows magnitude." },
  { id: "chart-annotation",    label: "Annotation system",       page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Threshold lines, target bands, event callouts, confidence intervals. The reusable annotation vocabulary that overlays any chart." },
  { id: "chart-maps",          label: "Geographic charts",       page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Texas county choropleths, TxDOT districts, US-state context, metro insets, dot-density and origin–destination flows." },
  { id: "map-legend",          label: "Map legend & attribution", page: "Data viz",  figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Legend kinds (choropleth, categorical, graduated symbol, bivariate, flow), scale bar, north arrow, and attribution overlays. Embeddable into chart-maps or a third-party basemap." },
  { id: "corridor-strip",      label: "Corridor strip",          page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Linear-referenced ribbon for a roadway, transit line, or river. Pavement condition, AADT, crash density, and event markers along a milepoint axis. Includes a transit-alignment variant." },
  { id: "focus-model",         label: "Focus model",             page: "Accessibility", figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Focus-ring spec across surfaces, keyboard nav patterns, skip links, focus-trap rules for dialogs vs. popovers." },
  { id: "breakpoints",         label: "Breakpoints",             page: "Accessibility", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Six-named breakpoint system (xs–2xl), grid columns + gutters per breakpoint, type-ramp specimens, reflow rules per family." },
  { id: "contrast-matrix",     label: "Contrast matrix",         page: "Accessibility", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Every text/surface pairing rendered as a swatch grid with measured AA/AAA pass marks, including non-text and disabled-state guidance." },
  { id: "motion-rtl",          label: "Motion & RTL",            page: "Accessibility", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Motion duration tokens, prefers-reduced-motion fallbacks per family, and which elements flip vs. stay in RTL languages." },
  { id: "data-tables",         label: "Research data tables",    page: "Data viz",   figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Sortable, footnoted tables with uncertainty cells. The chart counterpart for when readers need exact numbers." },
  { id: "rich-data-grid",      label: "Rich data grid",          page: "Data viz",   figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Interactive data grid for research apps — sticky header, row selection, expandable rows, column resize. Lineage: Ant Design Table, Microsoft Fluent 2 Web DataGrid, Fabric Rich-data-grid." },

  /* ─── Components — descriptions + tree ──────────────────────────── */
  { id: "descriptions",        label: "Descriptions",            page: "Components", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Key/value list for record summaries — horizontal, vertical, and bordered variants with section dividers and footnote cells. Lineage: Ant Descriptions, Microsoft Fluent 2 Web Field, Fabric Field." },
  { id: "tree",                label: "Tree",                    page: "Components", figma: null, styles: ["default"], darkMode: true,  status: "ready", blurb: "Indented hierarchy with expand/collapse, selection, and drag affordance. For corridor breakdowns, file trees, taxonomy browsers. Lineage: Ant Tree, Microsoft Fluent 2 Web Tree, Fabric Tree." },

  /* ─── Sectioning — tabs and side-sheet ────────────────────────── */
  { id: "tabs-horizontal",     label: "Tabs · horizontal",       page: "Sectioning", figma: null, styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Underline tabs (canonical default), segmented control, and pill tabs. Three tab styles, each tied to a style variant. Single-row, scroll-on-overflow. Width modes: Fixed (equal-width cells) and Intrinsic (content-fit). Lineage: Base Gallery Tabs (width-mode taxonomy + underline-as-default guardrail)." },
  { id: "tabs-vertical",       label: "Tabs · vertical",         page: "Sectioning", figma: null, styles: ["default","bold","elegant"], darkMode: true,  status: "ready", blurb: "Left-rail tabs for settings pages and split-view layouts. Section headers, descriptions, status badges, keyboard navigable." },
  { id: "side-sheet",          label: "Side sheet",              page: "Sectioning", figma: null, styles: ["default","bold","elegant"], darkMode: false, status: "ready", blurb: "Slide-in panel from the right edge for detail views, filters, edit forms. Scrim variant for modal context, inline variant for split-pane." },

  /* ─── Templates / Mockups — whole-page assemblies (Batch I) ─────── */
  { id: "tmpl-research-dashboard", label: "Research dashboard",  page: "Templates", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "PECAN-class data-app dashboard: filter strip, 4-stat row, corridor strip chart, top-projects table, district map, alerts rail. Composes 11 ready families. Lineage: Fabric page-templates + Apple HIG sidebar rhythm." },
  { id: "tmpl-document-detail",    label: "Document detail",     page: "Templates", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Long-form research record with metadata header, body, sticky TOC rail, related-link sidebar, references. Composes page-headers, data-tables, toc, description-list, buttons. Lineage: Apple HIG long-form + tti-docs editorial rhythm." },
  { id: "tmpl-settings-shell",     label: "Settings shell",      page: "Templates", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Vertical-tab settings page (Account / Workspace / Advanced) with profile-edit panel. Composes tabs-vertical, field-grid, form-text, buttons. Lineage: Apple HIG macOS Settings + Fabric pivot-page." },
  { id: "tmpl-list-detail-split",  label: "List · detail split", page: "Templates", figma: null, styles: ["default"], darkMode: false, status: "ready", blurb: "Mail-style two-pane: scrollable list with status dots on the left, selected detail on the right. Composes rich-data-grid rows, descriptions, buttons, badge-chip-tag. Interactive. Lineage: Apple HIG Mail / Fabric two-pane editor." },
  { id: "templates",           label: "Template index",          page: "Templates", figma: "/Templates-Mockups", styles: ["default","bold","elegant"], darkMode: false, status: "ready", blurb: "Whole-page assemblies showing how components compose — landing, news article, faculty profile, event." },

];
