// Auto-generated by scripts/build-geo.mjs — do not edit by hand.
// Re-run `npm run build:geo` if upstream source data changes.
//
// Sources:
//   - us-atlas@3 (npm; TIGER/Line 1:10m simplified)
//   - data/source/txdot-districts.geojson (TxDOT Boundaries
//     MapServer, layer 0; simplified 0.005 Visvalingam weight)
//
// Coordinate system: SVG pixel space inside the indicated viewBox.
// Projection: d3-geoAlbers (Texas) / d3-geoAlbersUsa (US).


// Compatibility barrel. The data now lives in per-concern modules so
// the TuxChartGeographic kind children can each load only what they
// render. Importing THIS barrel statically pulls all four modules —
// import the specific module instead when payload matters.
export * from "./texas-outline";
export * from "./texas-outline-polygon";
export * from "./txdot-districts";
export * from "./tx-metros";
