// Auto-generated by scripts/build-geo.mjs — do not edit by hand.
// Re-run `npm run build:geo` if upstream source data changes.
//
// Sources:
//   - us-atlas@3 (npm; TIGER/Line 1:10m simplified)
//   - data/source/txdot-districts.geojson (TxDOT Boundaries
//     MapServer, layer 0; simplified 0.005 Visvalingam weight)
//
// Coordinate system: SVG pixel space inside the indicated viewBox.
// Projection: d3-geoAlbers (Texas) / d3-geoAlbersUsa (US).


export interface TxMetro {
  code: string;
  name: string;
  lat: number;
  lng: number;
  /** Projected pixel coords inside TX_VIEWBOX. */
  x: number;
  y: number;
}

export const txMetros: ReadonlyArray<TxMetro> = [{"code":"DFW","name":"Dallas–Fort Worth","lat":32.776,"lng":-96.797,"x":402.3,"y":139.4},{"code":"HOU","name":"Houston","lat":29.76,"lng":-95.37,"x":451.9,"y":251},{"code":"SAT","name":"San Antonio","lat":29.424,"lng":-98.494,"x":350.7,"y":266.4},{"code":"AUS","name":"Austin","lat":30.267,"lng":-97.743,"x":374.5,"y":234.3},{"code":"ELP","name":"El Paso","lat":31.76,"lng":-106.487,"x":95.6,"y":173},{"code":"MCA","name":"McAllen","lat":26.203,"lng":-98.23,"x":361.2,"y":387},{"code":"LBB","name":"Lubbock","lat":33.578,"lng":-101.855,"x":243.8,"y":110.3}];
