/**
 * tuxCatalog — the single source of truth for the component catalog.
 *
 * Drives the app.vue sidebar navTree (Components / Reports / Visualizations
 * sections), the /components index card grid, the command-palette jump list
 * (via navTree), and the homepage catalog count. tests/tux-catalog.test.ts
 * enforces agreement between this list, app/components/ on disk, the page
 * routes, and the design/components.md catalog tables — add a component
 * anywhere and the test tells you every other place it must appear.
 *
 * INTERNAL_COMPONENTS are recursive children or showcase primitives that
 * deliberately have no catalog entry of their own.
 */

export type TuxCatalogFamily = "components" | "reports" | "visualizations";

export interface TuxCatalogEntry {
  /** Component or composable name as auto-imported, e.g. "TuxAlert". */
  name: string;
  /** Showcase route. Clustered families share one route. */
  to: string;
  /** Sidebar/palette icon (validated against app/utils/lucide-names.ts). */
  icon: string;
  /** Sidebar grouping. */
  family: TuxCatalogFamily;
  kind: "component" | "composable";
  /** What it wraps — mirrors the design/components.md "Wraps" column. */
  wraps: string;
  /** One-line card description for the /components index. */
  blurb: string;
}

export const INTERNAL_COMPONENTS = [
  "TuxExample",         // showcase primitive, used on every component page
  "TuxDocsSidebarNode", // recursive child of TuxDocsSidebar
  "TuxTreeNode",        // recursive child of TuxTree
  "TuxRuleBuilderGroup",// recursive child of TuxRuleBuilder
];

export const tuxCatalog: TuxCatalogEntry[] = [
  { name: "TuxAbstract", to: "/components/research-publishing", icon: "lucide:file-text", family: "components", kind: "component", wraps: "tux native",
    blurb: "Structured academic abstract block." },
  { name: "TuxAccordion", to: "/components/accordion", icon: "lucide:chevrons-up-down", family: "components", kind: "component", wraps: "tux native",
    blurb: "FAQ + publication disclosure — native details/summary, zero-JS, single-mode + slot composition." },
  { name: "TuxAcknowledgments", to: "/components/research-publishing", icon: "lucide:hand-heart", family: "components", kind: "component", wraps: "tux native",
    blurb: "Funding + acknowledgments + ethics block." },
  { name: "TuxAlert", to: "/components/alert", icon: "lucide:message-square", family: "components", kind: "component", wraps: "UAlert",
    blurb: "Docusaurus-style admonitions — 8 variants including compliance and tip." },
  { name: "TuxAlphaNav", to: "/components/alpha-nav", icon: "lucide:case-sensitive", family: "components", kind: "component", wraps: "tux native",
    blurb: "A–Z jump bar — anchor mode for in-page jumps, emit mode for filter-in-place." },
  { name: "TuxAnnouncementBanner", to: "/components/announcement-banner", icon: "lucide:megaphone", family: "components", kind: "component", wraps: "tux native",
    blurb: "Top-of-page dismissable strip for site-wide notices. localStorage-backed dismissal memory." },
  { name: "TuxAppFrame", to: "/components/app-frame", icon: "lucide:app-window", family: "components", kind: "component", wraps: "tux native",
    blurb: "Custom Tauri titlebar — traffic lights (Mac) / min-max-close (Win/Linux), brand + toolbar slots, drag regions. Replaces native window decoration." },
  { name: "TuxAppSwitcher", to: "/components/app-switcher", icon: "lucide:layout-grid", family: "components", kind: "component", wraps: "UPopover",
    blurb: "Waffle-button popover for hopping between TTI portals — registry-fed via useTuxApps(), registry order everywhere, current tile carries aria-current." },
  { name: "TuxArtifact", to: "/components/artifact", icon: "lucide:file-output", family: "components", kind: "component", wraps: "tux native",
    blurb: "AI output container — header + actions + body slot. Wraps generated code, docs, exported datasets." },
  { name: "TuxAuthorByline", to: "/components/research-publishing", icon: "lucide:users", family: "components", kind: "component", wraps: "tux native",
    blurb: "Multi-author byline with affiliations + ORCID." },
  { name: "TuxBadge", to: "/components/badge", icon: "lucide:badge", family: "components", kind: "component", wraps: "UBadge",
    blurb: "Classification tiers, lifecycle statuses, monospace tags, and facet counts." },
  { name: "TuxBetaRibbon", to: "/components/beta-ribbon", icon: "lucide:flag-triangle-right", family: "components", kind: "component", wraps: "tux native",
    blurb: "Environment label — corner ribbon, top stripe, or inline pill. preview/beta/dev tones." },
  { name: "TuxBigStat", to: "/components/big-stat", icon: "lucide:trending-up", family: "components", kind: "component", wraps: "tux native",
    blurb: "Single oversized metric — three sizes, three tones, three style variants." },
  { name: "TuxBlockquote", to: "/components/blockquote", icon: "lucide:quote", family: "components", kind: "component", wraps: "tux native",
    blurb: "Standalone pull quote — centered or magazine-style drop-cap. Variant-aware rule + face." },
  { name: "TuxBranchNav", to: "/components/branch-nav", icon: "lucide:git-branch", family: "components", kind: "component", wraps: "tux native",
    blurb: "‹ N of M › navigator for response alternatives. Lives in TuxChatMessage's #header-trailing slot." },
  { name: "TuxBreadcrumbs", to: "/components/breadcrumbs", icon: "lucide:chevrons-right", family: "components", kind: "component", wraps: "tux native",
    blurb: "Page-depth nav — home icon, italic intermediates, pipe rules collapsing to chevron on narrow." },
  { name: "TuxButton", to: "/components/button", icon: "lucide:rectangle-horizontal", family: "components", kind: "component", wraps: "UButton",
    blurb: "Semantic intent prop — primary, secondary, ghost, destructive (fills on hover)." },
  { name: "TuxCTA", to: "/components/cta", icon: "lucide:megaphone", family: "components", kind: "component", wraps: "tux native",
    blurb: "Big promotional block — three tones, three style variants, action slot." },
  { name: "TuxCallout", to: "/components/callout", icon: "lucide:flag-triangle-right", family: "components", kind: "component", wraps: "tux native",
    blurb: "Pulled-aside editorial accent — fact / stat / quote with style-variant left rule." },
  { name: "TuxCaptionedMedia", to: "/components/captioned-media", icon: "lucide:image", family: "components", kind: "component", wraps: "tux native",
    blurb: "Single image + caption + credit. 16:9 / 1:1 / 4:3 / 3:4 aspect, full / wide / right alignment." },
  { name: "TuxCard", to: "/components/card", icon: "lucide:square-stack", family: "components", kind: "component", wraps: "tux native",
    blurb: "Static or linked — linked mode has corner-drop hover + appearing arrow." },
  { name: "TuxCardCarousel", to: "/components/card-carousel", icon: "lucide:gallery-horizontal-end", family: "components", kind: "component", wraps: "UCarousel (embla) wrap",
    blurb: "Horizontal scroll of cards — eyebrow + display title + arrows + dots. Wraps UCarousel." },
  { name: "TuxCardSlab", to: "/components/card-slab", icon: "lucide:rows-3", family: "components", kind: "component", wraps: "tux native",
    blurb: "Full-bleed band of media-forward cards — \\\"browse our programs\\\" pattern, 2/3/4-up." },
  { name: "TuxCenterBadge", to: "/components/tti-identity", icon: "lucide:landmark", family: "components", kind: "component", wraps: "tux native",
    blurb: "TTI center / division marker." },
  { name: "TuxChartArea", to: "/visualizations/chart-area", icon: "lucide:area-chart", family: "visualizations", kind: "component", wraps: "tux native SVG",
    blurb: "Native SVG area chart — overlay or stacked variants, end-of-area labels, paired with TuxBigStat for the KPI-strip composition." },
  { name: "TuxChartBar", to: "/visualizations/chart-bar", icon: "lucide:bar-chart-3", family: "visualizations", kind: "component", wraps: "tux native SVG",
    blurb: "Native SVG bar chart — single / grouped / stacked variants, vertical or horizontal, optional comparison overlay (projection vs actual)." },
  { name: "TuxChartDonut", to: "/visualizations/chart-donut", icon: "lucide:pie-chart", family: "visualizations", kind: "component", wraps: "tux native SVG",
    blurb: "Share-of-total donut — center stat slot, slice-label colored to wedge, minSlice% auto-folds tiny slices into Other." },
  { name: "TuxChartFrame", to: "/visualizations/chart-line", icon: "lucide:frame", family: "visualizations", kind: "component", wraps: "tux native (editorial wrapper)",
    blurb: "Editorial wrapper that ties native chart components into the TUX type system." },
  { name: "TuxChartGauge", to: "/visualizations/chart-gauge", icon: "lucide:gauge", family: "visualizations", kind: "component", wraps: "tux native SVG",
    blurb: "270° arc gauge for single-target metrics — needle + tone bands, or radial-progress variant. Use sparingly." },
  { name: "TuxChartGeographic", to: "/visualizations/chart-geographic", icon: "lucide:map", family: "visualizations", kind: "component", wraps: "tux native (5-kind Texas map)",
    blurb: "Texas-flavored geographic charts." },
  { name: "TuxChartLine", to: "/visualizations/chart-line", icon: "lucide:line-chart", family: "visualizations", kind: "component", wraps: "tux native SVG",
    blurb: "Native SVG line chart — end-of-line value labels, optional previous-period overlay + confidence band, auto SR summary." },
  { name: "TuxChartScatter", to: "/visualizations/chart-scatter", icon: "lucide:scatter-chart", family: "visualizations", kind: "component", wraps: "tux native SVG",
    blurb: "Correlation plot — x vs y dots, optional linear-regression trendline + R², bubble-chart mode via per-point size." },
  { name: "TuxChartSunburst", to: "/visualizations/chart-sunburst", icon: "lucide:circle-dot", family: "visualizations", kind: "component", wraps: "tux native (two-ring radial)",
    blurb: "Radial counterpart to `TuxTreemap`." },
  { name: "TuxChatMessage", to: "/components/chat-message", icon: "lucide:message-square-text", family: "components", kind: "component", wraps: "tux native",
    blurb: "One conversation turn — user or assistant role, citations slot, tool row. Powers tti-ai-chat." },
  { name: "TuxCitationExport", to: "/components/research-publishing", icon: "lucide:download", family: "components", kind: "component", wraps: "UDropdownMenu",
    blurb: "Academic citation export menu." },
  { name: "TuxCitations", to: "/components/citations", icon: "lucide:quote", family: "components", kind: "component", wraps: "tux native",
    blurb: "Numbered source list under an assistant message — title + path + score in a 3-col grid." },
  { name: "TuxCodeBlock", to: "/components/code-block", icon: "lucide:code", family: "components", kind: "component", wraps: "Shiki",
    blurb: "Standalone Shiki code block — filename, line numbers, copy. Lazy-loads grammar on mount." },
  { name: "TuxCodeMaroon", to: "/components/code-maroon", icon: "lucide:siren", family: "components", kind: "component", wraps: "tux native",
    blurb: "Mandatory emergency alert banner — Rellis Code Maroon. Three severities, non-themed colors." },
  { name: "TuxCommandPalette", to: "/components/command-palette", icon: "lucide:command", family: "components", kind: "component", wraps: "tux native",
    blurb: "Global ⌘K jump — search + grouped commands + keyboard nav, native <dialog>." },
  { name: "TuxCommentThread", to: "/components/comment-thread", icon: "lucide:message-square-quote", family: "components", kind: "component", wraps: "tux native",
    blurb: "Peer-review / editorial threads — root + replies, @mentions, resolve/reopen, edit/delete own." },
  { name: "TuxComposer", to: "/components/composer", icon: "lucide:pencil-line", family: "components", kind: "component", wraps: "tux native",
    blurb: "Chat input with optional compliance scope banner — model picker, corpus attach, ⌘↵ send." },
  { name: "TuxConfirmDialog", to: "/components/forms-wrapper", icon: "lucide:square-check", family: "components", kind: "component", wraps: "TuxModal preset",
    blurb: "TuxModal preset for destructive-action confirmation." },
  { name: "TuxContactCard", to: "/components/contact-card", icon: "lucide:circle-user", family: "components", kind: "component", wraps: "tux native",
    blurb: "Directory card — portrait + name + role + typed contact rows. Vertical or horizontal." },
  { name: "TuxContextMeter", to: "/components/context-meter", icon: "lucide:gauge", family: "components", kind: "component", wraps: "UPopover",
    blurb: "Token-utilization meter — pill + conic ring + popover with input/output/cost. Tone-codes ok/warn/alert." },
  { name: "TuxContextPanel", to: "/components/context-panel", icon: "lucide:panel-right", family: "components", kind: "component", wraps: "tux native",
    blurb: "Right-rail surface for chat grounding context (corpus, retrieval, usage). Slot-driven chrome." },
  { name: "TuxConversationList", to: "/components/conversation-list", icon: "lucide:message-square", family: "components", kind: "component", wraps: "tux native",
    blurb: "Sidebar history of past conversations grouped by temporal bucket (TODAY / YESTERDAY / …)." },
  { name: "TuxCookieConsent", to: "/components/cookie-consent", icon: "lucide:cookie", family: "components", kind: "component", wraps: "tux native",
    blurb: "Privacy notice — bottom-right or full-width strip. localStorage-backed decision memory; categories slot." },
  { name: "TuxCorridorStrip", to: "/components/geospatial", icon: "lucide:route", family: "components", kind: "component", wraps: "tux native SVG",
    blurb: "Linear corridor visualization." },
  { name: "TuxDataTable", to: "/components/data-table", icon: "lucide:table-2", family: "components", kind: "component", wraps: "tux native",
    blurb: "Research-deliverable table — numbered caption, uncertainty cells (value ± CI), footnote anchors, totals row, source citation. Static (printable)." },
  { name: "TuxDescriptionList", to: "/components/description-list", icon: "lucide:list", family: "components", kind: "component", wraps: "tux native",
    blurb: "Term/definition pairs — native dl/dt/dd. Inline or stacked, editorial or data emphasis." },
  { name: "TuxDiagram", to: "/components/diagram", icon: "lucide:workflow", family: "components", kind: "component", wraps: "Mermaid",
    blurb: "Mermaid diagrams-as-code — flowcharts, sequences, ERDs. Lazy-loaded ~3MB; brand-themed." },
  { name: "TuxDocsSidebar", to: "/components/docs-sidebar", icon: "lucide:panel-left", family: "components", kind: "component", wraps: "tux native",
    blurb: "Hierarchical doc-site sidebar — collapsible sections, search filter, persisted collapse state." },
  { name: "TuxDropdown", to: "/components/site-nav", icon: "lucide:chevron-down", family: "components", kind: "component", wraps: "tux native",
    blurb: "Single-column dropdown from a top-bar nav item. Composes inside TuxSiteNav." },
  { name: "TuxEmptyState", to: "/components/empty-state", icon: "lucide:inbox", family: "components", kind: "component", wraps: "TuxCard composite",
    blurb: "No-data placeholder — tinted icon circle, title, description, CTA slot." },
  { name: "TuxErrorPage", to: "/components/error-page", icon: "lucide:circle-alert", family: "components", kind: "component", wraps: "tux native",
    blurb: "Full-page 404/500/403/503 template — display-type code, recovery actions, support slot." },
  { name: "TuxFAB", to: "/components/fab", icon: "lucide:circle-plus", family: "components", kind: "component", wraps: "tux native",
    blurb: "Floating Action Button. Material-pattern primary action; icon-only circle or extended pill. Honors safe-area-inset." },
  { name: "TuxFactoid", to: "/components/factoid", icon: "lucide:hash", family: "components", kind: "component", wraps: "tux native",
    blurb: "Institutional \\\"by the numbers\\\" — 3/4/5-up oversized stats, variant-aware numerals." },
  { name: "TuxFigureCaption", to: "/components/research-publishing", icon: "lucide:captions", family: "components", kind: "component", wraps: "tux native",
    blurb: "Auto-numbered caption for figures, tables, exhibits, equations." },
  { name: "TuxFileDropzone", to: "/components/forms-wrapper", icon: "lucide:cloud-upload", family: "components", kind: "component", wraps: "tux native",
    blurb: "Drag-and-drop file upload." },
  { name: "TuxFilterPanel", to: "/components/filter-panel", icon: "lucide:list-filter", family: "components", kind: "component", wraps: "tux native",
    blurb: "Left-rail facet panel — collapsible groups, checkbox lists with counts, applied-filter chips." },
  { name: "TuxFocusView", to: "/components/focus-view", icon: "lucide:focus", family: "components", kind: "component", wraps: "Teleport + native",
    blurb: "Full-viewport overlay for inspecting one piece of content — back + title + actions chrome, content slot. \\\"Open chart in focus mode.\\\"" },
  { name: "TuxFooter", to: "/components/footer", icon: "lucide:panel-bottom", family: "components", kind: "component", wraps: "tux native",
    blurb: "Unified institutional footer \\u2014 maroon marketing top (logo + address + social + columns) over the mandatory TAMUS legal strip." },
  { name: "TuxFootnote", to: "/components/research-publishing", icon: "lucide:asterisk", family: "components", kind: "component", wraps: "UPopover",
    blurb: "Inline footnote reference + hover preview." },
  { name: "TuxFormField", to: "/components/forms-wrapper", icon: "lucide:text-cursor-input", family: "components", kind: "component", wraps: "tux native",
    blurb: "Label + help + input + error stack." },
  { name: "TuxFundingSource", to: "/components/tti-identity", icon: "lucide:hand-coins", family: "components", kind: "component", wraps: "tux native",
    blurb: "Funder identity strip / chip." },
  { name: "TuxIconFeature", to: "/components/icon-feature", icon: "lucide:layout-grid", family: "components", kind: "component", wraps: "tux native",
    blurb: "Icon + headline + body grid — classic \\\"our services\\\" block, three tones, grid or list." },
  { name: "TuxIdentity", to: "/components/identity", icon: "lucide:flag", family: "components", kind: "component", wraps: "tux native",
    blurb: "Header lockup — logo + wordmark. Lockup or text-only, horizontal or stacked, three levels." },
  { name: "TuxInfiniteScroll", to: "/components/infinite-scroll", icon: "lucide:chevrons-down", family: "components", kind: "component", wraps: "tux native",
    blurb: "IntersectionObserver sentinel that auto-fetches the next page. Honors prefers-reduced-motion + keyboard fallback." },
  { name: "TuxInfoLabel", to: "/components/info-label", icon: "lucide:info", family: "components", kind: "component", wraps: "UPopover",
    blurb: "Form-field label with (i) help — hover or click popover with the explanation. For ITAR rubrics, retention classes, classifier metrics." },
  { name: "TuxInlineCitation", to: "/components/inline-citation", icon: "lucide:text-quote", family: "components", kind: "component", wraps: "UPopover",
    blurb: "Academic-style inline [N] citation pill — hover reveals title + URL + excerpt + score. Composes with TuxCitations footer list." },
  { name: "TuxKbd", to: "/components/kbd", icon: "lucide:keyboard", family: "components", kind: "component", wraps: "tux native",
    blurb: "Token-styled <kbd> for shortcut hints. Mac/PC modifier normalization, three sizes, combo + sequence forms." },
  { name: "TuxLab", to: "/components/tti-identity", icon: "lucide:flask-conical", family: "components", kind: "component", wraps: "tux native",
    blurb: "TTI lab / center identity card." },
  { name: "TuxLinkList", to: "/components/link-list", icon: "lucide:list-tree", family: "components", kind: "component", wraps: "tux native",
    blurb: "Categorized resource list — grouped headings, optional descriptions, featured-item left bar." },
  { name: "TuxLinkSlab", to: "/components/link-slab", icon: "lucide:menu", family: "components", kind: "component", wraps: "tux native",
    blurb: "Full-width band of prominent links — footer-of-section navigation, three tones." },
  { name: "TuxLoadMore", to: "/components/load-more", icon: "lucide:circle-plus", family: "components", kind: "component", wraps: "tux native",
    blurb: "Explicit \\\"Load more\\\" button + remaining count + terminal divider when all loaded. SEO-friendly middle ground." },
  { name: "TuxMapEmbed", to: "/components/geospatial", icon: "lucide:map", family: "components", kind: "component", wraps: "iframe / slot",
    blurb: "Library-agnostic map embed wrapper." },
  { name: "TuxMapLegend", to: "/components/geospatial", icon: "lucide:list-tree", family: "components", kind: "component", wraps: "tux native",
    blurb: "Standalone legend for embedded maps." },
  { name: "TuxMapMarker", to: "/components/geospatial", icon: "lucide:map-pin", family: "components", kind: "component", wraps: "tux native SVG",
    blurb: "Research-typed map marker." },
  { name: "TuxMarkdownEditor", to: "/components/forms-wrapper", icon: "lucide:pen-line", family: "components", kind: "component", wraps: "tux native (no deps)",
    blurb: "Textarea with markdown shortcuts." },
  { name: "TuxMcpEmbed", to: "/components/mcp-embed", icon: "lucide:plug", family: "components", kind: "component", wraps: "tux native",
    blurb: "Frame for interactive third-party MCP app output — app icon + name + window controls + skeleton. Sister to TuxArtifact." },
  { name: "TuxMediaSlab", to: "/components/media-slab", icon: "lucide:image-plus", family: "components", kind: "component", wraps: "tux native",
    blurb: "Full-bleed hero band — overlay (drama) or split (editorial), three heights, three tones." },
  { name: "TuxMegaMenu", to: "/components/site-nav", icon: "lucide:panels-top-left", family: "components", kind: "component", wraps: "tux native",
    blurb: "Full-width multi-column panel from a top-bar item, optional featured tile. Composes inside TuxSiteNav." },
  { name: "TuxMenuBar", to: "/components/menu-bar", icon: "lucide:menu", family: "components", kind: "component", wraps: "UDropdownMenu",
    blurb: "In-window File / Edit / View / Help menu strip for Windows / Linux Tauri shells. Skipped on Mac (system menu wins)." },
  { name: "TuxMetroInset", to: "/visualizations/chart-geographic", icon: "lucide:locate", family: "visualizations", kind: "component", wraps: "tux native (neighborhood grid)",
    blurb: "Neighborhood-grid inset for a single metro, intended for 4-up side-by-side layouts (Houston · DFW · Austin · San Antonio)." },
  { name: "TuxMobileFrame", to: "/components/mobile-frame", icon: "lucide:smartphone", family: "components", kind: "component", wraps: "tux native (CSS)",
    blurb: "Stylized device chrome for screenshots — iOS (iPhone) or Android (Pixel) via platform prop. Doc-only marketing helper." },
  { name: "TuxModal", to: "/components/modal", icon: "lucide:panel-top-open", family: "components", kind: "component", wraps: "UModal",
    blurb: "UModal with editorial rhythm — optional eyebrow, gold-bar underlined title." },
  { name: "TuxNewsCollection", to: "/components/news-collection", icon: "lucide:newspaper", family: "components", kind: "component", wraps: "tux native",
    blurb: "News article list — date + thumbnail + headline + dek + read-more, stacked or grid." },
  { name: "TuxPageHeader", to: "/components/page-header", icon: "lucide:pilcrow", family: "components", kind: "component", wraps: "tux native",
    blurb: "Eyebrow + gold-bar heading + subtitle — plain default, neutral or maroon panel, hero rhythm." },
  { name: "TuxPagination", to: "/components/pagination", icon: "lucide:list-ordered", family: "components", kind: "component", wraps: "tux native",
    blurb: "Page-number controls — squarified active page, ellipsis truncation, optional status line." },
  { name: "TuxPaperMeta", to: "/components/research-publishing", icon: "lucide:file-badge", family: "components", kind: "component", wraps: "tux native",
    blurb: "Academic paper metadata block." },
  { name: "TuxPhotoGrid", to: "/components/photo-grid", icon: "lucide:images", family: "components", kind: "component", wraps: "tux native",
    blurb: "Uniform image grid — photo (full color, captioned) or logo wall (grayscale-on-hover)." },
  { name: "TuxPopover", to: "/components/popover", icon: "lucide:message-square-more", family: "components", kind: "component", wraps: "UPopover",
    blurb: "Richer-than-tooltip floating panel — title + body + actions. Maroon hairline rule under title. Click default; hover for read-only." },
  { name: "TuxProgram", to: "/components/tti-identity", icon: "lucide:milestone", family: "components", kind: "component", wraps: "tux native",
    blurb: "Research-program identity card." },
  { name: "TuxProse", to: "/components/prose", icon: "lucide:text", family: "components", kind: "component", wraps: "tux native",
    blurb: "Typographic shell for long-form markdown — H1/H2/H3/p/list/code/table/blockquote rhythm in one wrapper." },
  { name: "TuxQACollection", to: "/components/qa-collection", icon: "lucide:message-circle-question-mark", family: "components", kind: "component", wraps: "tux native",
    blurb: "Long-form Q&A — always expanded, designed to be read top-to-bottom (companion to TuxAccordion)." },
  { name: "TuxRailNav", to: "/components/rail-nav", icon: "lucide:panel-left", family: "components", kind: "component", wraps: "tux (no U-primitive)",
    blurb: "Collapsible sidebar/rail navigation — native <details> disclosure groups (accessible without roleless aria-expanded), icon-only collapsed mode. tux-owned replacement for UNavigationMenu in app shells." },
  { name: "TuxReactionBar", to: "/components/reaction-bar", icon: "lucide:thumbs-up", family: "components", kind: "component", wraps: "tux native",
    blurb: "Light-touch helpful/question/disagree row. Lower friction than a feedback form; counts display-only." },
  { name: "TuxRemovableChip", to: "/components/removable-chip", icon: "lucide:tag", family: "components", kind: "component", wraps: "tux native",
    blurb: "Interactive dismissible chip — leading icon, three sizes, removable × or click-to-remove whole pill. Distinct from TuxBadge (decorative)." },
  { name: "TuxReportFrame", to: "/reports/frame", icon: "lucide:file-text", family: "reports", kind: "component", wraps: "tux native",
    blurb: "Page-sized canvas (letter / a4) for PDF + print. Stats, charts, prose go inside." },
  { name: "TuxReportPrintSheet", to: "/reports/print-sheet", icon: "lucide:printer", family: "reports", kind: "component", wraps: "useHead injection",
    blurb: "Drop-in print stylesheet; hides chrome, paginates with data-print-break attrs." },
  { name: "TuxReportWebFrame", to: "/reports/web-frame", icon: "lucide:globe", family: "reports", kind: "component", wraps: "tux native",
    blurb: "Long-form web-hosted narrative — cover, byline, lede, sticky TOC, body, footer." },
  { name: "TuxResearcher", to: "/components/tti-identity", icon: "lucide:user-round", family: "components", kind: "component", wraps: "tux native",
    blurb: "Researcher profile card." },
  { name: "TuxResultCount", to: "/components/result-count", icon: "lucide:sigma", family: "components", kind: "component", wraps: "tux native",
    blurb: "\\\"Showing 1–24 of 412 corridors · 24 per page\\\". Pairs with TuxPagination / TuxLoadMore / TuxInfiniteScroll." },
  { name: "TuxRichDataGrid", to: "/components/rich-data-grid", icon: "lucide:layout-grid", family: "components", kind: "component", wraps: "tux native",
    blurb: "Interactive data grid — sticky header, row selection, expandable detail, sort + filter chips, bulk-action bar. Landscape-class operational surfaces." },
  { name: "TuxRichTextEditor", to: "/components/rich-text-editor", icon: "lucide:pen-line", family: "components", kind: "component", wraps: "Tiptap + lowlight",
    blurb: "Canonical WYSIWYG — Tiptap-based, 7 toolbar groups, tables, task lists, source-mode toggle, full-screen, syntax highlighting." },
  { name: "TuxRuleBuilder", to: "/components/rule-builder", icon: "lucide:filter", family: "components", kind: "component", wraps: "tux native",
    blurb: "Relational query UI — field + operator + value rows, AND/OR groupers, nestable. Sister to faceted TuxFilterPanel." },
  { name: "TuxSearch", to: "/components/search", icon: "lucide:search", family: "components", kind: "component", wraps: "tux native",
    blurb: "Branded search bar — bordered input + uppercase action button. Regular / slim / focus state." },
  { name: "TuxSectionHeader", to: "/components/section-header", icon: "lucide:heading", family: "components", kind: "component", wraps: "tux native",
    blurb: "Editorial section heading — ALL-CAPS, tracked-out, maroon underline." },
  { name: "TuxShortcutsHelp", to: "/components/shortcuts-help", icon: "lucide:keyboard", family: "components", kind: "component", wraps: "tux native (<dialog>)",
    blurb: "Modal overlay listing every wired keyboard shortcut — combos vs sequences, opens on ?. Sibling to TuxCommandPalette." },
  { name: "TuxSidebarBlock", to: "/components/sidebar-block", icon: "lucide:panel-right", family: "components", kind: "component", wraps: "tux native",
    blurb: "Sidebar widget wrapper — eyebrow + maroon underline + content. Default/bordered/filled." },
  { name: "TuxSignupFeature", to: "/components/signup-feature", icon: "lucide:mail-plus", family: "components", kind: "component", wraps: "tux native",
    blurb: "Newsletter signup — email input + uppercase action + consent. Three tones, three style variants." },
  { name: "TuxSiteNav", to: "/components/site-nav", icon: "lucide:square-menu", family: "components", kind: "component", wraps: "tux native",
    blurb: "Top-bar with TuxIdentity + utility nav + primary nav. Hosts TuxDropdown / TuxMegaMenu items." },
  { name: "TuxSkeleton", to: "/components/skeleton", icon: "lucide:loader", family: "components", kind: "component", wraps: "tux native",
    blurb: "Loading-state placeholder — primitive shapes + 6 composed presets. Honors prefers-reduced-motion." },
  { name: "TuxSlideover", to: "/components/slideover", icon: "lucide:panel-right", family: "components", kind: "component", wraps: "tux native",
    blurb: "Edge-anchored drawer — row detail, filter panel, mobile nav, action sheet. Right/left/bottom anchors, native <dialog>." },
  { name: "TuxSparkline", to: "/visualizations/sparkline", icon: "lucide:trending-up", family: "visualizations", kind: "component", wraps: "tux native (inline SVG)",
    blurb: "Inline mini trend line — no axes, optional area fill, last-point dot, delta arrow. Native SVG." },
  { name: "TuxSplashScreen", to: "/components/splash-screen", icon: "lucide:loader-circle", family: "components", kind: "component", wraps: "tux native",
    blurb: "Branded app-launch overlay — brand mark + maroon hairline + status. Bridges Tauri window-show → Vue hydrate gap. Fades when loaded." },
  { name: "TuxSplitPane", to: "/components/split-pane", icon: "lucide:columns-2", family: "components", kind: "component", wraps: "tux native",
    blurb: "In-page master-detail layout — resizable list + detail + optional bottom pane. Width persists via localStorage. URL-bound selection." },
  { name: "TuxStatComparison", to: "/components/stat-comparison", icon: "lucide:arrow-up-right", family: "components", kind: "component", wraps: "tux native",
    blurb: "Before/after stat block with delta + tone. Direct or inverted polarity (down-is-good metrics). Row / stack / inline layouts." },
  { name: "TuxStepper", to: "/components/stepper", icon: "lucide:list-checks", family: "components", kind: "component", wraps: "tux native",
    blurb: "Numbered-circle multi-step indicator — funding application, IRB submission, study onboarding." },
  { name: "TuxSuggestionChips", to: "/components/suggestion-chips", icon: "lucide:sparkles", family: "components", kind: "component", wraps: "tux native",
    blurb: "Horizontal row of clickable prompt-suggestion chips. Empty-state composer or post-response follow-ups." },
  { name: "TuxTOC", to: "/components/toc", icon: "lucide:list-ordered", family: "components", kind: "component", wraps: "tux native",
    blurb: "Article table-of-contents — sticky right rail with IntersectionObserver-driven active state." },
  { name: "TuxTabBar", to: "/components/tab-bar", icon: "lucide:layout-panel-top", family: "components", kind: "component", wraps: "tux native",
    blurb: "Bottom-anchored 3-5 mobile tabs — icon + label, maroon top-edge active rule, safe-area-inset-bottom honored. Tauri Mobile target." },
  { name: "TuxTable", to: "/components/table", icon: "lucide:table", family: "components", kind: "component", wraps: "UTable",
    blurb: "UTable with tux chrome, automatic status-cell rendering via TuxBadge." },
  { name: "TuxTableCaption", to: "/components/research-publishing", icon: "lucide:table-properties", family: "components", kind: "component", wraps: "composes TuxFigureCaption",
    blurb: "Auto-numbered caption for tables." },
  { name: "TuxTabs", to: "/components/tabs", icon: "lucide:rectangle-vertical", family: "components", kind: "component", wraps: "UTabs",
    blurb: "Editorial tabs with maroon active underline. Horizontal + vertical orientations; `bold` intent for eyebrow-rhythm labels." },
  { name: "TuxTeachingPopover", to: "/components/teaching-popover", icon: "lucide:graduation-cap", family: "components", kind: "component", wraps: "tux native",
    blurb: "Onboarding/guided-tour tooltip — image, body, Next/Skip, step counter. On-brand variant for high emphasis." },
  { name: "TuxTestimonial", to: "/components/testimonial", icon: "lucide:message-circle-heart", family: "components", kind: "component", wraps: "tux native",
    blurb: "Attributed quotes with portrait + name + role — grid or row layout, three style variants." },
  { name: "TuxTooltip", to: "/components/tooltip", icon: "lucide:message-square-quote", family: "components", kind: "component", wraps: "UTooltip",
    blurb: "Keyboard-accessible hover-help with optional title + hairline rule. Tuned max-width (~22ch)." },
  { name: "TuxTree", to: "/components/tree", icon: "lucide:list-tree", family: "components", kind: "component", wraps: "tux native",
    blurb: "Hierarchical list — sitemap, corpus + filesystem browser, BI dataset explorer. Mono leaf labels, sand guide lines, persistence." },
  { name: "TuxTreemap", to: "/components/treemap", icon: "lucide:layout-dashboard", family: "components", kind: "component", wraps: "tux native",
    blurb: "Squarified hierarchical-size viz — Landscape's headline chart, drill-in, no external library." },
  { name: "TuxUserMenu", to: "/components/utility-cluster", icon: "lucide:circle-user", family: "components", kind: "component", wraps: "UDropdownMenu",
    blurb: "The suite's one identity affordance — cluster chip or rail-footer mount, state-complete (loading / signed-out / signed-in / local-only / error), law-fixed menu order." },
  { name: "TuxUtilityCluster", to: "/components/utility-cluster", icon: "lucide:layout-grid", family: "components", kind: "component", wraps: "tux (composes TuxAppSwitcher + TuxUserMenu)",
    blurb: "The trailing app-control cluster — search · notifications · theme · waffle · identity in law-fixed DOM order. Registry-fed waffle + role=status theme announcements." },
  { name: "TuxValidationSummary", to: "/components/forms-wrapper", icon: "lucide:circle-alert", family: "components", kind: "component", wraps: "tux native",
    blurb: "Error list at the top of a long form." },
  { name: "TuxVizEmbed", to: "/visualizations/embed", icon: "lucide:bar-chart-3", family: "visualizations", kind: "component", wraps: "sandboxed <iframe> + poster fallback",
    blurb: "Tableau / Power BI / Apache Superset / Grafana iframe wrapper with poster fallback." },
  { name: "TuxVizGrid", to: "/visualizations/grid", icon: "lucide:grid-2x2", family: "visualizations", kind: "component", wraps: "tux native (CSS Grid layout shell)",
    blurb: "Small-multiples layout primitive — 2/3/4-up panes with shared editorial header. Container-queried." },
  { name: "TuxVizRPlot", to: "/visualizations/rplot", icon: "lucide:square-sigma", family: "visualizations", kind: "component", wraps: "<img> / <object> / <iframe>",
    blurb: "R artifact wrapper — image / svg / htmlwidget — with source-line caption gutter." },
  { name: "useTuxPlatform", to: "/components/app-frame", icon: "lucide:monitor-smartphone", family: "components", kind: "composable", wraps: "composable",
    blurb: "Host-OS + Tauri detection for platform-adaptive chrome." },
  { name: "useTuxRipple", to: "/components/ripple", icon: "lucide:circle-dot", family: "components", kind: "composable", wraps: "composable",
    blurb: "Composable: Material-style tap-feedback ripple on a target element. Opt-in only; honors prefers-reduced-motion." },
  { name: "useTuxSwipe", to: "/components/swipe", icon: "lucide:move-horizontal", family: "components", kind: "composable", wraps: "composable",
    blurb: "Composable: pointer/touch swipe detection with directional callbacks. Requires a11y-pair button per platform-awareness doctrine." },];

/** Count of catalogued components (composables excluded) — homepage + README figure. */
export const tuxComponentCount = tuxCatalog.filter((e) => e.kind === "component").length;
