/**
 * scripts/extract-brand.mjs — generate kit/env/brand.env from
 * design/tokens.json.
 *
 * The flat KEY=#hex artifact for consumers that theme through shell / Go
 * templates / Python instead of CSS (the Forgejo overlay's
 * apply-branding.sh, compose-stack `make brand` fan-outs, bot-avatar
 * generators). Pattern adopted from collab-hub-stack's extract-brand.sh
 * — including its fail-safety: write to a temp file and rename only on
 * full success, so an interrupted run can never leave a truncated
 * brand.env that would half-theme every downstream app.
 *
 * Every value is a resolved LITERAL (references chased through
 * {token.path} aliases) — env consumers can't resolve var() chains.
 * Committed (like kit/css/) so it ships over git dep + jsDelivr:
 *   cdn.jsdelivr.net/gh/ttitamu/tti-ux@<tag>/kit/env/brand.env
 *
 * Run via `npm run build:brand-env` (also invoked by build:tokens's
 * npm-script chain if wired there).
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const TOKENS_JSON = path.join(ROOT, "design/tokens.json");
const OUT = path.join(ROOT, "kit/env/brand.env");

const tokens = JSON.parse(fs.readFileSync(TOKENS_JSON, "utf8"));

/** Read a `{ "$value": ... }` leaf or bare value. */
const val = (node) => (node && typeof node === "object" ? node.$value : node);

/** Resolve `{a.b.c}` references to their literal value, recursively. */
function resolve(v, seen = new Set()) {
  if (typeof v !== "string") return v;
  const m = v.match(/^\{([^}]+)\}$/);
  if (!m) return v;
  const pathStr = m[1];
  if (seen.has(pathStr)) throw new Error(`circular token reference: ${pathStr}`);
  seen.add(pathStr);
  let node = tokens;
  for (const key of pathStr.split(".")) {
    node = node?.[key];
    if (node == null) throw new Error(`unresolvable token reference: {${pathStr}}`);
  }
  return resolve(val(node), seen);
}

const envKey = (s) => s.toUpperCase().replace(/-/g, "_");

const lines = [
  "# GENERATED by scripts/extract-brand.mjs from design/tokens.json — do not hand-edit.",
  `# Source of truth: design/tokens.json (tti-ux). Regenerate: npm run build:brand-env`,
  "# Flat resolved literals for shell/Go/Python consumers. Naming:",
  "#   TUX_<THEME>_<GROUP>_<TOKEN>  e.g. TUX_TTI_BRAND_PRIMARY, TUX_TTI_DARK_SURFACE_PAGE",
  "# The on-brand rule: content on *_BRAND_FILL uses TUX_TEXT_ON_BRAND (theme-invariant).",
  "",
];

// Theme-scoped groups every non-CSS consumer needs.
const GROUPS = ["brand", "surface", "text", "semantic"];
for (const [themeName, theme] of Object.entries(tokens.themes)) {
  // Placeholder institution themes aren't emitted to CSS either.
  if (!["tti", "tti-dark", "tti-hc"].includes(themeName)) continue;
  for (const groupName of GROUPS) {
    const group = theme[groupName];
    if (!group) continue;
    for (const [tokenName, node] of Object.entries(group)) {
      if (tokenName.startsWith("$") || tokenName.startsWith("_")) continue;
      const v = resolve(val(node));
      if (typeof v !== "string") continue;
      lines.push(`TUX_${envKey(themeName)}_${envKey(groupName)}_${envKey(tokenName)}=${v}`);
    }
  }
  lines.push("");
}

// Theme-invariant conveniences.
lines.push("# Theme-invariant");
lines.push(`TUX_TEXT_ON_BRAND=${resolve(val(tokens.themes.tti.text["on-brand"]))}`);
lines.push(`TUX_FONT_BODY=${resolve(val(tokens.globals.font.body))}`);
lines.push(`TUX_FONT_DISPLAY=${resolve(val(tokens.globals.font.display))}`);
lines.push(`TUX_FONT_BOLD=${resolve(val(tokens.globals.font.bold))}`);
lines.push(`TUX_FONT_MONO=${resolve(val(tokens.globals.font.mono))}`);
lines.push("");

// Fail-safe write: temp file + atomic rename (collab-hub's discipline).
fs.mkdirSync(path.dirname(OUT), { recursive: true });
const tmp = path.join(os.tmpdir(), `brand.env.${process.pid}`);
fs.writeFileSync(tmp, lines.join("\n"));
fs.renameSync(tmp, OUT);
console.log(`Wrote ${path.relative(ROOT, OUT)} (${lines.filter((l) => l.includes("=")).length} keys)`);
