// GENERATED FILE — do not edit. Source: design/tokens.json via scripts/build-framework-targets.mjs (npm run build:framework).
//
// Resolved design-token literals for .NET consumers (WPF, MAUI,
// Blazor, report generators). One static class per theme; token
// names are the CSS custom-property names without the leading
// dashes, PascalCased ("brand-primary" -> BrandPrimary). The All
// dictionary keeps the original kebab names for dynamic lookup.

namespace Tti.Tux;

public static class TuxTokens
{
    /// <summary>Theme "tti".</summary>
    public static class Tti
    {
        public const string TtiMaroon = "#5C0025";
        public const string TtiMaroonDeep = "#500000";
        public const string TtiGold = "#DDAC37";
        public const string TtiGoldDeep = "#DCAA37";
        public const string TtiNavy = "#15457E";
        public const string TtiTeal = "#4A8892";
        public const string TtiSage = "#66814F";
        public const string TtiCharcoal = "#221F1F";
        public const string Neutral0 = "#FFFFFF";
        public const string Neutral50 = "#FAFAFA";
        public const string Neutral100 = "#F5F5F5";
        public const string Neutral150 = "#EFEEED";
        public const string Neutral200 = "#E7E6E6";
        public const string Neutral250 = "#DCDBD8";
        public const string Neutral300 = "#D1D2D4";
        public const string Neutral400 = "#A5A5A5";
        public const string Neutral450 = "#9B9A96";
        public const string Neutral500 = "#939597";
        public const string Neutral550 = "#86847F";
        public const string Neutral600 = "#7E7E7E";
        public const string Neutral650 = "#6B6964";
        public const string Neutral700 = "#5D5D5D";
        public const string Neutral750 = "#535048";
        public const string Neutral800 = "#4C4C4E";
        public const string Neutral850 = "#3A3833";
        public const string Neutral900 = "#221F1F";
        public const string Neutral1000 = "#000000";
        public const string BrandPrimary = "#5C0025";
        public const string BrandPrimaryDeep = "#500000";
        public const string BrandAccent = "#DDAC37";
        public const string BrandAccentDeep = "#DCAA37";
        public const string BrandSecondary = "#15457E";
        public const string BrandFill = "#5C0025";
        public const string BrandAccentInk = "#2A0E15";
        public const string BrandAccentShade = "#A87B1F";
        public const string SurfacePage = "#FFFFFF";
        public const string SurfaceRaised = "#FFFFFF";
        public const string SurfaceSunken = "#F5F5F5";
        public const string SurfaceBorder = "#E7E6E6";
        public const string SurfaceBorderSubtle = "#EFEEED";
        public const string TextPrimary = "#221F1F";
        public const string TextSecondary = "#424242";
        public const string TextMuted = "#525252";
        public const string TextInverse = "#FFFFFF";
        public const string TextBrand = "#5C0025";
        public const string TextOnBrand = "#FFFFFF";
        public const string ColorSuccess = "#3D5328";
        public const string ColorWarning = "#DDAC37";
        public const string ColorDanger = "#5C0025";
        public const string ColorError = "#A02828";
        public const string ColorInfo = "#1F5D66";
        public const string FontBody = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontDisplay = "\"Oswald\", \"Helvetica Neue Condensed\", \"Impact\", \"Arial Narrow\", sans-serif";
        public const string FontBold = "\"Work Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontElegant = "Georgia, \"Times New Roman\", Times, serif";
        public const string FontSans = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontMono = "\"JetBrains Mono\", \"SFMono-Regular\", Consolas, \"Liberation Mono\", monospace";
        public const string TrackingTight = "-0.01em";
        public const string TrackingNormal = "0";
        public const string TrackingWide = "0.05em";
        public const string TrackingWider = "0.10em";
        public const string ShadowSm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)";
        public const string ShadowMd = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)";
        public const string ShadowLg = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)";
        public const string FocusRingOuter = "#5C0025";
        public const string FocusRingInner = "#F2E6C9";
        public const string ShadowFocus = "0 0 0 2px #F2E6C9, 0 0 0 4px #5C0025";
        public const string ElevationFlat = "none";
        public const string ElevationRest = "0 1px 2px 0 rgba(0, 0, 0, 0.05)";
        public const string ElevationHover = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)";
        public const string ElevationOverlay = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)";
        public const string ElevationPinned = "0 4px 6px -2px rgba(0, 0, 0, 0.06)";
        public const string RadiusNone = "0";
        public const string RadiusSm = "0.125rem";
        public const string RadiusMd = "0.375rem";
        public const string RadiusLg = "0.5rem";
        public const string RadiusXl = "0.75rem";
        public const string RadiusFull = "9999px";
        public const string MotionFast = "0.15s";
        public const string MotionBase = "0.25s";
        public const string MotionSlow = "0.35s";
        public const string EaseStandard = "cubic-bezier(0.2, 0.55, 0.4, 0.9)";
        public const string EaseEmphasis = "cubic-bezier(0.2, 0.8, 0.2, 1.2)";
        public const string EaseExit = "cubic-bezier(0.4, 0, 0.6, 1)";
        public const string EaseSurvey = "cubic-bezier(0.4, 0.0, 0.2, 1.0)";
        public const string EaseCorridor = "cubic-bezier(0.2, 0.0, 0.0, 1.0)";
        public const string EaseArrival = "cubic-bezier(0.0, 0.0, 0.2, 1.0)";
        public const string Space0 = "0";
        public const string Space2 = "2px";
        public const string Space4 = "4px";
        public const string Space8 = "8px";
        public const string Space10 = "10px";
        public const string Space12 = "12px";
        public const string Space16 = "16px";
        public const string Space24 = "24px";
        public const string Space32 = "32px";
        public const string Space40 = "40px";
        public const string Space48 = "48px";
        public const string Space64 = "64px";
        public const string LayoutContentMax = "80rem";
        public const string LayoutContentWide = "96rem";
        public const string LayoutProseMax = "72ch";
        public const string RhythmTight = "4px";
        public const string RhythmSnug = "8px";
        public const string RhythmNormal = "12px";
        public const string RhythmLoose = "16px";
        public const string RhythmRoomy = "24px";
        public const string WashBrand4 = "rgba(92, 0, 37, 0.04)";
        public const string WashBrand6 = "rgba(92, 0, 37, 0.06)";
        public const string WashBrand8 = "rgba(92, 0, 37, 0.08)";
        public const string WashBrand12 = "rgba(92, 0, 37, 0.12)";
        public const string WashBrand18 = "rgba(92, 0, 37, 0.18)";
        public const string WashBrand22 = "rgba(92, 0, 37, 0.22)";
        public const string WashBrand35 = "rgba(92, 0, 37, 0.35)";
        public const string ColorMaroon50 = "#fbf3f6";
        public const string ColorMaroon100 = "#f5e0e7";
        public const string ColorMaroon200 = "#eab5c3";
        public const string ColorMaroon300 = "#db859e";
        public const string ColorMaroon400 = "#b14a6c";
        public const string ColorMaroon500 = "#5c0025";
        public const string ColorMaroon600 = "#4d001f";
        public const string ColorMaroon700 = "#3d0018";
        public const string ColorMaroon800 = "#2e0012";
        public const string ColorMaroon900 = "#1f000c";
        public const string ColorMaroon950 = "#150008";
        public const string ColorGold50 = "#fdf9ee";
        public const string ColorGold100 = "#faf0d2";
        public const string ColorGold200 = "#f4dfa1";
        public const string ColorGold300 = "#ecca6f";
        public const string ColorGold400 = "#e3ba4f";
        public const string ColorGold500 = "#ddac37";
        public const string ColorGold600 = "#b58a23";
        public const string ColorGold700 = "#8a691b";
        public const string ColorGold800 = "#604812";
        public const string ColorGold900 = "#3f300b";
        public const string ColorGold950 = "#271e07";
        public const string Chart1 = "#5C0025";
        public const string Chart2 = "#3F5A6F";
        public const string Chart3 = "#C7973C";
        public const string Chart4 = "#6B8E5A";
        public const string Chart5 = "#8C5A3C";
        public const string Chart6 = "#5C7080";
        public const string Chart7 = "#A33A3A";
        public const string Chart8 = "#3C5A87";
        public const string Chart9 = "#6E5A7E";
        public const string Chart10 = "#7E7350";
        public const string MapSeqMaroon1 = "#F1E4E0";
        public const string MapSeqMaroon2 = "#DDB7AC";
        public const string MapSeqMaroon3 = "#C58675";
        public const string MapSeqMaroon4 = "#9E483A";
        public const string MapSeqMaroon5 = "#500000";
        public const string MapSeqSlate1 = "#E2E7EC";
        public const string MapSeqSlate2 = "#B7C2CC";
        public const string MapSeqSlate3 = "#7E94A4";
        public const string MapSeqSlate4 = "#52677A";
        public const string MapSeqSlate5 = "#283544";
        public const string MapOutline = "#E7E6E6";
        public const string MapFlow = "#5C0025";

        public static readonly System.Collections.Generic.IReadOnlyDictionary<string, string> All =
            new System.Collections.Generic.Dictionary<string, string>
            {
                ["tti-maroon"] = "#5C0025",
                ["tti-maroon-deep"] = "#500000",
                ["tti-gold"] = "#DDAC37",
                ["tti-gold-deep"] = "#DCAA37",
                ["tti-navy"] = "#15457E",
                ["tti-teal"] = "#4A8892",
                ["tti-sage"] = "#66814F",
                ["tti-charcoal"] = "#221F1F",
                ["neutral-0"] = "#FFFFFF",
                ["neutral-50"] = "#FAFAFA",
                ["neutral-100"] = "#F5F5F5",
                ["neutral-150"] = "#EFEEED",
                ["neutral-200"] = "#E7E6E6",
                ["neutral-250"] = "#DCDBD8",
                ["neutral-300"] = "#D1D2D4",
                ["neutral-400"] = "#A5A5A5",
                ["neutral-450"] = "#9B9A96",
                ["neutral-500"] = "#939597",
                ["neutral-550"] = "#86847F",
                ["neutral-600"] = "#7E7E7E",
                ["neutral-650"] = "#6B6964",
                ["neutral-700"] = "#5D5D5D",
                ["neutral-750"] = "#535048",
                ["neutral-800"] = "#4C4C4E",
                ["neutral-850"] = "#3A3833",
                ["neutral-900"] = "#221F1F",
                ["neutral-1000"] = "#000000",
                ["brand-primary"] = "#5C0025",
                ["brand-primary-deep"] = "#500000",
                ["brand-accent"] = "#DDAC37",
                ["brand-accent-deep"] = "#DCAA37",
                ["brand-secondary"] = "#15457E",
                ["brand-fill"] = "#5C0025",
                ["brand-accent-ink"] = "#2A0E15",
                ["brand-accent-shade"] = "#A87B1F",
                ["surface-page"] = "#FFFFFF",
                ["surface-raised"] = "#FFFFFF",
                ["surface-sunken"] = "#F5F5F5",
                ["surface-border"] = "#E7E6E6",
                ["surface-border-subtle"] = "#EFEEED",
                ["text-primary"] = "#221F1F",
                ["text-secondary"] = "#424242",
                ["text-muted"] = "#525252",
                ["text-inverse"] = "#FFFFFF",
                ["text-brand"] = "#5C0025",
                ["text-on-brand"] = "#FFFFFF",
                ["color-success"] = "#3D5328",
                ["color-warning"] = "#DDAC37",
                ["color-danger"] = "#5C0025",
                ["color-error"] = "#A02828",
                ["color-info"] = "#1F5D66",
                ["font-body"] = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-display"] = "\"Oswald\", \"Helvetica Neue Condensed\", \"Impact\", \"Arial Narrow\", sans-serif",
                ["font-bold"] = "\"Work Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-elegant"] = "Georgia, \"Times New Roman\", Times, serif",
                ["font-sans"] = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-mono"] = "\"JetBrains Mono\", \"SFMono-Regular\", Consolas, \"Liberation Mono\", monospace",
                ["tracking-tight"] = "-0.01em",
                ["tracking-normal"] = "0",
                ["tracking-wide"] = "0.05em",
                ["tracking-wider"] = "0.10em",
                ["shadow-sm"] = "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                ["shadow-md"] = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)",
                ["shadow-lg"] = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)",
                ["focus-ring-outer"] = "#5C0025",
                ["focus-ring-inner"] = "#F2E6C9",
                ["shadow-focus"] = "0 0 0 2px #F2E6C9, 0 0 0 4px #5C0025",
                ["elevation-flat"] = "none",
                ["elevation-rest"] = "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                ["elevation-hover"] = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)",
                ["elevation-overlay"] = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)",
                ["elevation-pinned"] = "0 4px 6px -2px rgba(0, 0, 0, 0.06)",
                ["radius-none"] = "0",
                ["radius-sm"] = "0.125rem",
                ["radius-md"] = "0.375rem",
                ["radius-lg"] = "0.5rem",
                ["radius-xl"] = "0.75rem",
                ["radius-full"] = "9999px",
                ["motion-fast"] = "0.15s",
                ["motion-base"] = "0.25s",
                ["motion-slow"] = "0.35s",
                ["ease-standard"] = "cubic-bezier(0.2, 0.55, 0.4, 0.9)",
                ["ease-emphasis"] = "cubic-bezier(0.2, 0.8, 0.2, 1.2)",
                ["ease-exit"] = "cubic-bezier(0.4, 0, 0.6, 1)",
                ["ease-survey"] = "cubic-bezier(0.4, 0.0, 0.2, 1.0)",
                ["ease-corridor"] = "cubic-bezier(0.2, 0.0, 0.0, 1.0)",
                ["ease-arrival"] = "cubic-bezier(0.0, 0.0, 0.2, 1.0)",
                ["space-0"] = "0",
                ["space-2"] = "2px",
                ["space-4"] = "4px",
                ["space-8"] = "8px",
                ["space-10"] = "10px",
                ["space-12"] = "12px",
                ["space-16"] = "16px",
                ["space-24"] = "24px",
                ["space-32"] = "32px",
                ["space-40"] = "40px",
                ["space-48"] = "48px",
                ["space-64"] = "64px",
                ["layout-content-max"] = "80rem",
                ["layout-content-wide"] = "96rem",
                ["layout-prose-max"] = "72ch",
                ["rhythm-tight"] = "4px",
                ["rhythm-snug"] = "8px",
                ["rhythm-normal"] = "12px",
                ["rhythm-loose"] = "16px",
                ["rhythm-roomy"] = "24px",
                ["wash-brand-4"] = "rgba(92, 0, 37, 0.04)",
                ["wash-brand-6"] = "rgba(92, 0, 37, 0.06)",
                ["wash-brand-8"] = "rgba(92, 0, 37, 0.08)",
                ["wash-brand-12"] = "rgba(92, 0, 37, 0.12)",
                ["wash-brand-18"] = "rgba(92, 0, 37, 0.18)",
                ["wash-brand-22"] = "rgba(92, 0, 37, 0.22)",
                ["wash-brand-35"] = "rgba(92, 0, 37, 0.35)",
                ["color-maroon-50"] = "#fbf3f6",
                ["color-maroon-100"] = "#f5e0e7",
                ["color-maroon-200"] = "#eab5c3",
                ["color-maroon-300"] = "#db859e",
                ["color-maroon-400"] = "#b14a6c",
                ["color-maroon-500"] = "#5c0025",
                ["color-maroon-600"] = "#4d001f",
                ["color-maroon-700"] = "#3d0018",
                ["color-maroon-800"] = "#2e0012",
                ["color-maroon-900"] = "#1f000c",
                ["color-maroon-950"] = "#150008",
                ["color-gold-50"] = "#fdf9ee",
                ["color-gold-100"] = "#faf0d2",
                ["color-gold-200"] = "#f4dfa1",
                ["color-gold-300"] = "#ecca6f",
                ["color-gold-400"] = "#e3ba4f",
                ["color-gold-500"] = "#ddac37",
                ["color-gold-600"] = "#b58a23",
                ["color-gold-700"] = "#8a691b",
                ["color-gold-800"] = "#604812",
                ["color-gold-900"] = "#3f300b",
                ["color-gold-950"] = "#271e07",
                ["chart-1"] = "#5C0025",
                ["chart-2"] = "#3F5A6F",
                ["chart-3"] = "#C7973C",
                ["chart-4"] = "#6B8E5A",
                ["chart-5"] = "#8C5A3C",
                ["chart-6"] = "#5C7080",
                ["chart-7"] = "#A33A3A",
                ["chart-8"] = "#3C5A87",
                ["chart-9"] = "#6E5A7E",
                ["chart-10"] = "#7E7350",
                ["map-seq-maroon-1"] = "#F1E4E0",
                ["map-seq-maroon-2"] = "#DDB7AC",
                ["map-seq-maroon-3"] = "#C58675",
                ["map-seq-maroon-4"] = "#9E483A",
                ["map-seq-maroon-5"] = "#500000",
                ["map-seq-slate-1"] = "#E2E7EC",
                ["map-seq-slate-2"] = "#B7C2CC",
                ["map-seq-slate-3"] = "#7E94A4",
                ["map-seq-slate-4"] = "#52677A",
                ["map-seq-slate-5"] = "#283544",
                ["map-outline"] = "#E7E6E6",
                ["map-flow"] = "#5C0025",
            };
    }

    /// <summary>Theme "tti-dark".</summary>
    public static class TtiDark
    {
        public const string TtiMaroon = "#5C0025";
        public const string TtiMaroonDeep = "#500000";
        public const string TtiGold = "#DDAC37";
        public const string TtiGoldDeep = "#DCAA37";
        public const string TtiNavy = "#15457E";
        public const string TtiTeal = "#4A8892";
        public const string TtiSage = "#66814F";
        public const string TtiCharcoal = "#221F1F";
        public const string Neutral0 = "#FFFFFF";
        public const string Neutral50 = "#FAFAFA";
        public const string Neutral100 = "#F5F5F5";
        public const string Neutral150 = "#EFEEED";
        public const string Neutral200 = "#E7E6E6";
        public const string Neutral250 = "#DCDBD8";
        public const string Neutral300 = "#D1D2D4";
        public const string Neutral400 = "#A5A5A5";
        public const string Neutral450 = "#9B9A96";
        public const string Neutral500 = "#939597";
        public const string Neutral550 = "#86847F";
        public const string Neutral600 = "#7E7E7E";
        public const string Neutral650 = "#6B6964";
        public const string Neutral700 = "#5D5D5D";
        public const string Neutral750 = "#535048";
        public const string Neutral800 = "#4C4C4E";
        public const string Neutral850 = "#3A3833";
        public const string Neutral900 = "#221F1F";
        public const string Neutral1000 = "#000000";
        public const string BrandPrimary = "#6BB4C0";
        public const string BrandPrimaryDeep = "#5B9CA8";
        public const string BrandAccent = "#DDAC37";
        public const string BrandAccentDeep = "#F0C362";
        public const string BrandSecondary = "#8ab7e2";
        public const string BrandFill = "#5C0025";
        public const string BrandAccentInk = "#2A0E15";
        public const string BrandAccentShade = "#A87B1F";
        public const string SurfacePage = "#15100F";
        public const string SurfaceRaised = "#221F1F";
        public const string SurfaceSunken = "#0B0908";
        public const string SurfaceBorder = "#3D3A3A";
        public const string SurfaceBorderSubtle = "#2E2B2A";
        public const string TextPrimary = "#FAFAFA";
        public const string TextSecondary = "#D1D2D4";
        public const string TextMuted = "#B5B5B5";
        public const string TextInverse = "#221F1F";
        public const string TextBrand = "#5B9CA8";
        public const string TextOnBrand = "#FFFFFF";
        public const string ColorSuccess = "#ABCC8E";
        public const string ColorWarning = "#F5D98A";
        public const string ColorDanger = "#e795a8";
        public const string ColorError = "#F59292";
        public const string ColorInfo = "#9BD4E0";
        public const string FontBody = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontDisplay = "\"Oswald\", \"Helvetica Neue Condensed\", \"Impact\", \"Arial Narrow\", sans-serif";
        public const string FontBold = "\"Work Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontElegant = "Georgia, \"Times New Roman\", Times, serif";
        public const string FontSans = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontMono = "\"JetBrains Mono\", \"SFMono-Regular\", Consolas, \"Liberation Mono\", monospace";
        public const string TrackingTight = "-0.01em";
        public const string TrackingNormal = "0";
        public const string TrackingWide = "0.05em";
        public const string TrackingWider = "0.10em";
        public const string ShadowSm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)";
        public const string ShadowMd = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)";
        public const string ShadowLg = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)";
        public const string FocusRingOuter = "#6BB4C0";
        public const string FocusRingInner = "#3D2E0F";
        public const string ShadowFocus = "0 0 0 2px #3D2E0F, 0 0 0 4px #6BB4C0";
        public const string ElevationFlat = "none";
        public const string ElevationRest = "0 1px 2px 0 rgba(0, 0, 0, 0.05)";
        public const string ElevationHover = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)";
        public const string ElevationOverlay = "0 10px 15px -3px rgba(0, 0, 0, 0.20), 0 4px 6px -2px rgba(0, 0, 0, 0.12)";
        public const string ElevationPinned = "0 4px 6px -2px rgba(0, 0, 0, 0.18)";
        public const string RadiusNone = "0";
        public const string RadiusSm = "0.125rem";
        public const string RadiusMd = "0.375rem";
        public const string RadiusLg = "0.5rem";
        public const string RadiusXl = "0.75rem";
        public const string RadiusFull = "9999px";
        public const string MotionFast = "0.15s";
        public const string MotionBase = "0.25s";
        public const string MotionSlow = "0.35s";
        public const string EaseStandard = "cubic-bezier(0.2, 0.55, 0.4, 0.9)";
        public const string EaseEmphasis = "cubic-bezier(0.2, 0.8, 0.2, 1.2)";
        public const string EaseExit = "cubic-bezier(0.4, 0, 0.6, 1)";
        public const string EaseSurvey = "cubic-bezier(0.4, 0.0, 0.2, 1.0)";
        public const string EaseCorridor = "cubic-bezier(0.2, 0.0, 0.0, 1.0)";
        public const string EaseArrival = "cubic-bezier(0.0, 0.0, 0.2, 1.0)";
        public const string Space0 = "0";
        public const string Space2 = "2px";
        public const string Space4 = "4px";
        public const string Space8 = "8px";
        public const string Space10 = "10px";
        public const string Space12 = "12px";
        public const string Space16 = "16px";
        public const string Space24 = "24px";
        public const string Space32 = "32px";
        public const string Space40 = "40px";
        public const string Space48 = "48px";
        public const string Space64 = "64px";
        public const string LayoutContentMax = "80rem";
        public const string LayoutContentWide = "96rem";
        public const string LayoutProseMax = "72ch";
        public const string RhythmTight = "4px";
        public const string RhythmSnug = "8px";
        public const string RhythmNormal = "12px";
        public const string RhythmLoose = "16px";
        public const string RhythmRoomy = "24px";
        public const string WashBrand4 = "rgba(107, 180, 192, 0.04)";
        public const string WashBrand6 = "rgba(107, 180, 192, 0.06)";
        public const string WashBrand8 = "rgba(107, 180, 192, 0.08)";
        public const string WashBrand12 = "rgba(107, 180, 192, 0.12)";
        public const string WashBrand18 = "rgba(107, 180, 192, 0.18)";
        public const string WashBrand22 = "rgba(107, 180, 192, 0.22)";
        public const string WashBrand35 = "rgba(107, 180, 192, 0.35)";
        public const string ColorMaroon50 = "#fbf3f6";
        public const string ColorMaroon100 = "#f5e0e7";
        public const string ColorMaroon200 = "#eab5c3";
        public const string ColorMaroon300 = "#db859e";
        public const string ColorMaroon400 = "#6BB4C0";
        public const string ColorMaroon500 = "#5c0025";
        public const string ColorMaroon600 = "#4d001f";
        public const string ColorMaroon700 = "#3d0018";
        public const string ColorMaroon800 = "#2e0012";
        public const string ColorMaroon900 = "#1f000c";
        public const string ColorMaroon950 = "#150008";
        public const string ColorGold50 = "#fdf9ee";
        public const string ColorGold100 = "#faf0d2";
        public const string ColorGold200 = "#f4dfa1";
        public const string ColorGold300 = "#ecca6f";
        public const string ColorGold400 = "#e3ba4f";
        public const string ColorGold500 = "#ddac37";
        public const string ColorGold600 = "#b58a23";
        public const string ColorGold700 = "#8a691b";
        public const string ColorGold800 = "#604812";
        public const string ColorGold900 = "#3f300b";
        public const string ColorGold950 = "#271e07";
        public const string Chart1 = "#c47585";
        public const string Chart2 = "#6B8DA3";
        public const string Chart3 = "#E0BC60";
        public const string Chart4 = "#93B57E";
        public const string Chart5 = "#B58463";
        public const string Chart6 = "#8AA0B2";
        public const string Chart7 = "#D67272";
        public const string Chart8 = "#6E8FBE";
        public const string Chart9 = "#A08CB4";
        public const string Chart10 = "#B0A578";
        public const string MapSeqMaroon1 = "#3D1110";
        public const string MapSeqMaroon2 = "#702C28";
        public const string MapSeqMaroon3 = "#A14A3D";
        public const string MapSeqMaroon4 = "#C97058";
        public const string MapSeqMaroon5 = "#E89B7E";
        public const string MapSeqSlate1 = "#1A2129";
        public const string MapSeqSlate2 = "#3F5A6F";
        public const string MapSeqSlate3 = "#6F8294";
        public const string MapSeqSlate4 = "#9CADBD";
        public const string MapSeqSlate5 = "#C2D0DE";
        public const string MapOutline = "rgba(255, 255, 255, 0.22)";
        public const string MapFlow = "#E89B7E";
        public const string ColorBrandPrimary = "#6BB4C0";
        public const string ColorBrandPrimaryDeep = "#5B9CA8";
        public const string ColorBrandAccent = "#DDAC37";
        public const string ColorBrandAccentDeep = "#F0C362";
        public const string ColorBrandSecondary = "#8ab7e2";
        public const string ColorBrandFill = "#5C0025";
        public const string ColorSurfacePage = "#15100F";
        public const string ColorSurfaceRaised = "#221F1F";
        public const string ColorSurfaceSunken = "#0B0908";
        public const string ColorSurfaceBorder = "#3D3A3A";
        public const string ColorSurfaceBorderSubtle = "#2E2B2A";
        public const string ColorTextPrimary = "#FAFAFA";
        public const string ColorTextSecondary = "#D1D2D4";
        public const string ColorTextMuted = "#B5B5B5";
        public const string ColorTextInverse = "#221F1F";
        public const string ColorTextBrand = "#5B9CA8";
        public const string ColorTextOnBrand = "#FFFFFF";

        public static readonly System.Collections.Generic.IReadOnlyDictionary<string, string> All =
            new System.Collections.Generic.Dictionary<string, string>
            {
                ["tti-maroon"] = "#5C0025",
                ["tti-maroon-deep"] = "#500000",
                ["tti-gold"] = "#DDAC37",
                ["tti-gold-deep"] = "#DCAA37",
                ["tti-navy"] = "#15457E",
                ["tti-teal"] = "#4A8892",
                ["tti-sage"] = "#66814F",
                ["tti-charcoal"] = "#221F1F",
                ["neutral-0"] = "#FFFFFF",
                ["neutral-50"] = "#FAFAFA",
                ["neutral-100"] = "#F5F5F5",
                ["neutral-150"] = "#EFEEED",
                ["neutral-200"] = "#E7E6E6",
                ["neutral-250"] = "#DCDBD8",
                ["neutral-300"] = "#D1D2D4",
                ["neutral-400"] = "#A5A5A5",
                ["neutral-450"] = "#9B9A96",
                ["neutral-500"] = "#939597",
                ["neutral-550"] = "#86847F",
                ["neutral-600"] = "#7E7E7E",
                ["neutral-650"] = "#6B6964",
                ["neutral-700"] = "#5D5D5D",
                ["neutral-750"] = "#535048",
                ["neutral-800"] = "#4C4C4E",
                ["neutral-850"] = "#3A3833",
                ["neutral-900"] = "#221F1F",
                ["neutral-1000"] = "#000000",
                ["brand-primary"] = "#6BB4C0",
                ["brand-primary-deep"] = "#5B9CA8",
                ["brand-accent"] = "#DDAC37",
                ["brand-accent-deep"] = "#F0C362",
                ["brand-secondary"] = "#8ab7e2",
                ["brand-fill"] = "#5C0025",
                ["brand-accent-ink"] = "#2A0E15",
                ["brand-accent-shade"] = "#A87B1F",
                ["surface-page"] = "#15100F",
                ["surface-raised"] = "#221F1F",
                ["surface-sunken"] = "#0B0908",
                ["surface-border"] = "#3D3A3A",
                ["surface-border-subtle"] = "#2E2B2A",
                ["text-primary"] = "#FAFAFA",
                ["text-secondary"] = "#D1D2D4",
                ["text-muted"] = "#B5B5B5",
                ["text-inverse"] = "#221F1F",
                ["text-brand"] = "#5B9CA8",
                ["text-on-brand"] = "#FFFFFF",
                ["color-success"] = "#ABCC8E",
                ["color-warning"] = "#F5D98A",
                ["color-danger"] = "#e795a8",
                ["color-error"] = "#F59292",
                ["color-info"] = "#9BD4E0",
                ["font-body"] = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-display"] = "\"Oswald\", \"Helvetica Neue Condensed\", \"Impact\", \"Arial Narrow\", sans-serif",
                ["font-bold"] = "\"Work Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-elegant"] = "Georgia, \"Times New Roman\", Times, serif",
                ["font-sans"] = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-mono"] = "\"JetBrains Mono\", \"SFMono-Regular\", Consolas, \"Liberation Mono\", monospace",
                ["tracking-tight"] = "-0.01em",
                ["tracking-normal"] = "0",
                ["tracking-wide"] = "0.05em",
                ["tracking-wider"] = "0.10em",
                ["shadow-sm"] = "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                ["shadow-md"] = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)",
                ["shadow-lg"] = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)",
                ["focus-ring-outer"] = "#6BB4C0",
                ["focus-ring-inner"] = "#3D2E0F",
                ["shadow-focus"] = "0 0 0 2px #3D2E0F, 0 0 0 4px #6BB4C0",
                ["elevation-flat"] = "none",
                ["elevation-rest"] = "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                ["elevation-hover"] = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)",
                ["elevation-overlay"] = "0 10px 15px -3px rgba(0, 0, 0, 0.20), 0 4px 6px -2px rgba(0, 0, 0, 0.12)",
                ["elevation-pinned"] = "0 4px 6px -2px rgba(0, 0, 0, 0.18)",
                ["radius-none"] = "0",
                ["radius-sm"] = "0.125rem",
                ["radius-md"] = "0.375rem",
                ["radius-lg"] = "0.5rem",
                ["radius-xl"] = "0.75rem",
                ["radius-full"] = "9999px",
                ["motion-fast"] = "0.15s",
                ["motion-base"] = "0.25s",
                ["motion-slow"] = "0.35s",
                ["ease-standard"] = "cubic-bezier(0.2, 0.55, 0.4, 0.9)",
                ["ease-emphasis"] = "cubic-bezier(0.2, 0.8, 0.2, 1.2)",
                ["ease-exit"] = "cubic-bezier(0.4, 0, 0.6, 1)",
                ["ease-survey"] = "cubic-bezier(0.4, 0.0, 0.2, 1.0)",
                ["ease-corridor"] = "cubic-bezier(0.2, 0.0, 0.0, 1.0)",
                ["ease-arrival"] = "cubic-bezier(0.0, 0.0, 0.2, 1.0)",
                ["space-0"] = "0",
                ["space-2"] = "2px",
                ["space-4"] = "4px",
                ["space-8"] = "8px",
                ["space-10"] = "10px",
                ["space-12"] = "12px",
                ["space-16"] = "16px",
                ["space-24"] = "24px",
                ["space-32"] = "32px",
                ["space-40"] = "40px",
                ["space-48"] = "48px",
                ["space-64"] = "64px",
                ["layout-content-max"] = "80rem",
                ["layout-content-wide"] = "96rem",
                ["layout-prose-max"] = "72ch",
                ["rhythm-tight"] = "4px",
                ["rhythm-snug"] = "8px",
                ["rhythm-normal"] = "12px",
                ["rhythm-loose"] = "16px",
                ["rhythm-roomy"] = "24px",
                ["wash-brand-4"] = "rgba(107, 180, 192, 0.04)",
                ["wash-brand-6"] = "rgba(107, 180, 192, 0.06)",
                ["wash-brand-8"] = "rgba(107, 180, 192, 0.08)",
                ["wash-brand-12"] = "rgba(107, 180, 192, 0.12)",
                ["wash-brand-18"] = "rgba(107, 180, 192, 0.18)",
                ["wash-brand-22"] = "rgba(107, 180, 192, 0.22)",
                ["wash-brand-35"] = "rgba(107, 180, 192, 0.35)",
                ["color-maroon-50"] = "#fbf3f6",
                ["color-maroon-100"] = "#f5e0e7",
                ["color-maroon-200"] = "#eab5c3",
                ["color-maroon-300"] = "#db859e",
                ["color-maroon-400"] = "#6BB4C0",
                ["color-maroon-500"] = "#5c0025",
                ["color-maroon-600"] = "#4d001f",
                ["color-maroon-700"] = "#3d0018",
                ["color-maroon-800"] = "#2e0012",
                ["color-maroon-900"] = "#1f000c",
                ["color-maroon-950"] = "#150008",
                ["color-gold-50"] = "#fdf9ee",
                ["color-gold-100"] = "#faf0d2",
                ["color-gold-200"] = "#f4dfa1",
                ["color-gold-300"] = "#ecca6f",
                ["color-gold-400"] = "#e3ba4f",
                ["color-gold-500"] = "#ddac37",
                ["color-gold-600"] = "#b58a23",
                ["color-gold-700"] = "#8a691b",
                ["color-gold-800"] = "#604812",
                ["color-gold-900"] = "#3f300b",
                ["color-gold-950"] = "#271e07",
                ["chart-1"] = "#c47585",
                ["chart-2"] = "#6B8DA3",
                ["chart-3"] = "#E0BC60",
                ["chart-4"] = "#93B57E",
                ["chart-5"] = "#B58463",
                ["chart-6"] = "#8AA0B2",
                ["chart-7"] = "#D67272",
                ["chart-8"] = "#6E8FBE",
                ["chart-9"] = "#A08CB4",
                ["chart-10"] = "#B0A578",
                ["map-seq-maroon-1"] = "#3D1110",
                ["map-seq-maroon-2"] = "#702C28",
                ["map-seq-maroon-3"] = "#A14A3D",
                ["map-seq-maroon-4"] = "#C97058",
                ["map-seq-maroon-5"] = "#E89B7E",
                ["map-seq-slate-1"] = "#1A2129",
                ["map-seq-slate-2"] = "#3F5A6F",
                ["map-seq-slate-3"] = "#6F8294",
                ["map-seq-slate-4"] = "#9CADBD",
                ["map-seq-slate-5"] = "#C2D0DE",
                ["map-outline"] = "rgba(255, 255, 255, 0.22)",
                ["map-flow"] = "#E89B7E",
                ["color-brand-primary"] = "#6BB4C0",
                ["color-brand-primary-deep"] = "#5B9CA8",
                ["color-brand-accent"] = "#DDAC37",
                ["color-brand-accent-deep"] = "#F0C362",
                ["color-brand-secondary"] = "#8ab7e2",
                ["color-brand-fill"] = "#5C0025",
                ["color-surface-page"] = "#15100F",
                ["color-surface-raised"] = "#221F1F",
                ["color-surface-sunken"] = "#0B0908",
                ["color-surface-border"] = "#3D3A3A",
                ["color-surface-border-subtle"] = "#2E2B2A",
                ["color-text-primary"] = "#FAFAFA",
                ["color-text-secondary"] = "#D1D2D4",
                ["color-text-muted"] = "#B5B5B5",
                ["color-text-inverse"] = "#221F1F",
                ["color-text-brand"] = "#5B9CA8",
                ["color-text-on-brand"] = "#FFFFFF",
            };
    }

    /// <summary>Theme "tti-hc".</summary>
    public static class TtiHc
    {
        public const string TtiMaroon = "#5C0025";
        public const string TtiMaroonDeep = "#500000";
        public const string TtiGold = "#DDAC37";
        public const string TtiGoldDeep = "#DCAA37";
        public const string TtiNavy = "#15457E";
        public const string TtiTeal = "#4A8892";
        public const string TtiSage = "#66814F";
        public const string TtiCharcoal = "#221F1F";
        public const string Neutral0 = "#FFFFFF";
        public const string Neutral50 = "#FAFAFA";
        public const string Neutral100 = "#F5F5F5";
        public const string Neutral150 = "#EFEEED";
        public const string Neutral200 = "#E7E6E6";
        public const string Neutral250 = "#DCDBD8";
        public const string Neutral300 = "#D1D2D4";
        public const string Neutral400 = "#A5A5A5";
        public const string Neutral450 = "#9B9A96";
        public const string Neutral500 = "#939597";
        public const string Neutral550 = "#86847F";
        public const string Neutral600 = "#7E7E7E";
        public const string Neutral650 = "#6B6964";
        public const string Neutral700 = "#5D5D5D";
        public const string Neutral750 = "#535048";
        public const string Neutral800 = "#4C4C4E";
        public const string Neutral850 = "#3A3833";
        public const string Neutral900 = "#221F1F";
        public const string Neutral1000 = "#000000";
        public const string BrandPrimary = "#500000";
        public const string BrandPrimaryDeep = "#3A0000";
        public const string BrandAccent = "#DCAA37";
        public const string BrandAccentDeep = "#B88A21";
        public const string BrandSecondary = "#000000";
        public const string BrandFill = "#500000";
        public const string BrandAccentInk = "#2A0E15";
        public const string BrandAccentShade = "#A87B1F";
        public const string SurfacePage = "#FFFFFF";
        public const string SurfaceRaised = "#FFFFFF";
        public const string SurfaceSunken = "#F0F0F0";
        public const string SurfaceBorder = "#5D5D5D";
        public const string SurfaceBorderSubtle = "#5D5D5D";
        public const string TextPrimary = "#000000";
        public const string TextSecondary = "#221F1F";
        public const string TextMuted = "#4D4D4D";
        public const string TextInverse = "#FFFFFF";
        public const string TextBrand = "#500000";
        public const string TextOnBrand = "#FFFFFF";
        public const string ColorSuccess = "#3D5328";
        public const string ColorWarning = "#DDAC37";
        public const string ColorDanger = "#500000";
        public const string ColorError = "#A02828";
        public const string ColorInfo = "#1F5D66";
        public const string FontBody = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontDisplay = "\"Oswald\", \"Helvetica Neue Condensed\", \"Impact\", \"Arial Narrow\", sans-serif";
        public const string FontBold = "\"Work Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontElegant = "Georgia, \"Times New Roman\", Times, serif";
        public const string FontSans = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif";
        public const string FontMono = "\"JetBrains Mono\", \"SFMono-Regular\", Consolas, \"Liberation Mono\", monospace";
        public const string TrackingTight = "-0.01em";
        public const string TrackingNormal = "0";
        public const string TrackingWide = "0.05em";
        public const string TrackingWider = "0.10em";
        public const string ShadowSm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)";
        public const string ShadowMd = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)";
        public const string ShadowLg = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)";
        public const string FocusRingOuter = "#000000";
        public const string FocusRingInner = "#FFFFFF";
        public const string ShadowFocus = "0 0 0 2px #FFFFFF, 0 0 0 5px #000000";
        public const string ElevationFlat = "none";
        public const string ElevationRest = "none";
        public const string ElevationHover = "none";
        public const string ElevationOverlay = "0 0 0 2px #5D5D5D";
        public const string ElevationPinned = "0 0 0 1px #5D5D5D";
        public const string RadiusNone = "0";
        public const string RadiusSm = "0.125rem";
        public const string RadiusMd = "0.375rem";
        public const string RadiusLg = "0.5rem";
        public const string RadiusXl = "0.75rem";
        public const string RadiusFull = "9999px";
        public const string MotionFast = "0.15s";
        public const string MotionBase = "0.25s";
        public const string MotionSlow = "0.35s";
        public const string EaseStandard = "cubic-bezier(0.2, 0.55, 0.4, 0.9)";
        public const string EaseEmphasis = "cubic-bezier(0.2, 0.8, 0.2, 1.2)";
        public const string EaseExit = "cubic-bezier(0.4, 0, 0.6, 1)";
        public const string EaseSurvey = "cubic-bezier(0.4, 0.0, 0.2, 1.0)";
        public const string EaseCorridor = "cubic-bezier(0.2, 0.0, 0.0, 1.0)";
        public const string EaseArrival = "cubic-bezier(0.0, 0.0, 0.2, 1.0)";
        public const string Space0 = "0";
        public const string Space2 = "2px";
        public const string Space4 = "4px";
        public const string Space8 = "8px";
        public const string Space10 = "10px";
        public const string Space12 = "12px";
        public const string Space16 = "16px";
        public const string Space24 = "24px";
        public const string Space32 = "32px";
        public const string Space40 = "40px";
        public const string Space48 = "48px";
        public const string Space64 = "64px";
        public const string LayoutContentMax = "80rem";
        public const string LayoutContentWide = "96rem";
        public const string LayoutProseMax = "72ch";
        public const string RhythmTight = "4px";
        public const string RhythmSnug = "8px";
        public const string RhythmNormal = "12px";
        public const string RhythmLoose = "16px";
        public const string RhythmRoomy = "24px";
        public const string WashBrand4 = "rgba(80, 0, 0, 0.04)";
        public const string WashBrand6 = "rgba(80, 0, 0, 0.06)";
        public const string WashBrand8 = "rgba(80, 0, 0, 0.08)";
        public const string WashBrand12 = "rgba(80, 0, 0, 0.12)";
        public const string WashBrand18 = "rgba(80, 0, 0, 0.18)";
        public const string WashBrand22 = "rgba(80, 0, 0, 0.22)";
        public const string WashBrand35 = "rgba(80, 0, 0, 0.35)";
        public const string ColorMaroon50 = "#fbf3f6";
        public const string ColorMaroon100 = "#f5e0e7";
        public const string ColorMaroon200 = "#eab5c3";
        public const string ColorMaroon300 = "#db859e";
        public const string ColorMaroon400 = "#500000";
        public const string ColorMaroon500 = "#500000";
        public const string ColorMaroon600 = "#4d001f";
        public const string ColorMaroon700 = "#3d0018";
        public const string ColorMaroon800 = "#2e0012";
        public const string ColorMaroon900 = "#1f000c";
        public const string ColorMaroon950 = "#150008";
        public const string ColorGold50 = "#fdf9ee";
        public const string ColorGold100 = "#faf0d2";
        public const string ColorGold200 = "#f4dfa1";
        public const string ColorGold300 = "#ecca6f";
        public const string ColorGold400 = "#e3ba4f";
        public const string ColorGold500 = "#ddac37";
        public const string ColorGold600 = "#b58a23";
        public const string ColorGold700 = "#8a691b";
        public const string ColorGold800 = "#604812";
        public const string ColorGold900 = "#3f300b";
        public const string ColorGold950 = "#271e07";
        public const string Chart1 = "#000000";
        public const string Chart2 = "#500000";
        public const string Chart3 = "#5D5D5D";
        public const string Chart4 = "#8A6915";
        public const string Chart5 = "#4A4A4A";
        public const string Chart6 = "#1F5D66";
        public const string Chart7 = "#6B0000";
        public const string Chart8 = "#2A2A2A";
        public const string Chart9 = "#6E5A7E";
        public const string Chart10 = "#7E7350";
        public const string MapSeqMaroon1 = "#FFFFFF";
        public const string MapSeqMaroon2 = "#C8C8C8";
        public const string MapSeqMaroon3 = "#8A8A8A";
        public const string MapSeqMaroon4 = "#4A4A4A";
        public const string MapSeqMaroon5 = "#000000";
        public const string MapSeqSlate1 = "#FFFFFF";
        public const string MapSeqSlate2 = "#C8C8C8";
        public const string MapSeqSlate3 = "#8A8A8A";
        public const string MapSeqSlate4 = "#4A4A4A";
        public const string MapSeqSlate5 = "#000000";
        public const string MapOutline = "#000000";
        public const string MapFlow = "#000000";
        public const string ColorBrandPrimary = "#500000";
        public const string ColorBrandPrimaryDeep = "#3A0000";
        public const string ColorBrandAccent = "#DCAA37";
        public const string ColorBrandAccentDeep = "#B88A21";
        public const string ColorBrandSecondary = "#000000";
        public const string ColorBrandFill = "#500000";
        public const string ColorSurfacePage = "#FFFFFF";
        public const string ColorSurfaceRaised = "#FFFFFF";
        public const string ColorSurfaceSunken = "#F0F0F0";
        public const string ColorSurfaceBorder = "#5D5D5D";
        public const string ColorSurfaceBorderSubtle = "#5D5D5D";
        public const string ColorTextPrimary = "#000000";
        public const string ColorTextSecondary = "#221F1F";
        public const string ColorTextMuted = "#4D4D4D";
        public const string ColorTextInverse = "#FFFFFF";
        public const string ColorTextBrand = "#500000";
        public const string ColorTextOnBrand = "#FFFFFF";

        public static readonly System.Collections.Generic.IReadOnlyDictionary<string, string> All =
            new System.Collections.Generic.Dictionary<string, string>
            {
                ["tti-maroon"] = "#5C0025",
                ["tti-maroon-deep"] = "#500000",
                ["tti-gold"] = "#DDAC37",
                ["tti-gold-deep"] = "#DCAA37",
                ["tti-navy"] = "#15457E",
                ["tti-teal"] = "#4A8892",
                ["tti-sage"] = "#66814F",
                ["tti-charcoal"] = "#221F1F",
                ["neutral-0"] = "#FFFFFF",
                ["neutral-50"] = "#FAFAFA",
                ["neutral-100"] = "#F5F5F5",
                ["neutral-150"] = "#EFEEED",
                ["neutral-200"] = "#E7E6E6",
                ["neutral-250"] = "#DCDBD8",
                ["neutral-300"] = "#D1D2D4",
                ["neutral-400"] = "#A5A5A5",
                ["neutral-450"] = "#9B9A96",
                ["neutral-500"] = "#939597",
                ["neutral-550"] = "#86847F",
                ["neutral-600"] = "#7E7E7E",
                ["neutral-650"] = "#6B6964",
                ["neutral-700"] = "#5D5D5D",
                ["neutral-750"] = "#535048",
                ["neutral-800"] = "#4C4C4E",
                ["neutral-850"] = "#3A3833",
                ["neutral-900"] = "#221F1F",
                ["neutral-1000"] = "#000000",
                ["brand-primary"] = "#500000",
                ["brand-primary-deep"] = "#3A0000",
                ["brand-accent"] = "#DCAA37",
                ["brand-accent-deep"] = "#B88A21",
                ["brand-secondary"] = "#000000",
                ["brand-fill"] = "#500000",
                ["brand-accent-ink"] = "#2A0E15",
                ["brand-accent-shade"] = "#A87B1F",
                ["surface-page"] = "#FFFFFF",
                ["surface-raised"] = "#FFFFFF",
                ["surface-sunken"] = "#F0F0F0",
                ["surface-border"] = "#5D5D5D",
                ["surface-border-subtle"] = "#5D5D5D",
                ["text-primary"] = "#000000",
                ["text-secondary"] = "#221F1F",
                ["text-muted"] = "#4D4D4D",
                ["text-inverse"] = "#FFFFFF",
                ["text-brand"] = "#500000",
                ["text-on-brand"] = "#FFFFFF",
                ["color-success"] = "#3D5328",
                ["color-warning"] = "#DDAC37",
                ["color-danger"] = "#500000",
                ["color-error"] = "#A02828",
                ["color-info"] = "#1F5D66",
                ["font-body"] = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-display"] = "\"Oswald\", \"Helvetica Neue Condensed\", \"Impact\", \"Arial Narrow\", sans-serif",
                ["font-bold"] = "\"Work Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-elegant"] = "Georgia, \"Times New Roman\", Times, serif",
                ["font-sans"] = "\"Open Sans\", \"Helvetica Neue\", Arial, sans-serif",
                ["font-mono"] = "\"JetBrains Mono\", \"SFMono-Regular\", Consolas, \"Liberation Mono\", monospace",
                ["tracking-tight"] = "-0.01em",
                ["tracking-normal"] = "0",
                ["tracking-wide"] = "0.05em",
                ["tracking-wider"] = "0.10em",
                ["shadow-sm"] = "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
                ["shadow-md"] = "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.04)",
                ["shadow-lg"] = "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)",
                ["focus-ring-outer"] = "#000000",
                ["focus-ring-inner"] = "#FFFFFF",
                ["shadow-focus"] = "0 0 0 2px #FFFFFF, 0 0 0 5px #000000",
                ["elevation-flat"] = "none",
                ["elevation-rest"] = "none",
                ["elevation-hover"] = "none",
                ["elevation-overlay"] = "0 0 0 2px #5D5D5D",
                ["elevation-pinned"] = "0 0 0 1px #5D5D5D",
                ["radius-none"] = "0",
                ["radius-sm"] = "0.125rem",
                ["radius-md"] = "0.375rem",
                ["radius-lg"] = "0.5rem",
                ["radius-xl"] = "0.75rem",
                ["radius-full"] = "9999px",
                ["motion-fast"] = "0.15s",
                ["motion-base"] = "0.25s",
                ["motion-slow"] = "0.35s",
                ["ease-standard"] = "cubic-bezier(0.2, 0.55, 0.4, 0.9)",
                ["ease-emphasis"] = "cubic-bezier(0.2, 0.8, 0.2, 1.2)",
                ["ease-exit"] = "cubic-bezier(0.4, 0, 0.6, 1)",
                ["ease-survey"] = "cubic-bezier(0.4, 0.0, 0.2, 1.0)",
                ["ease-corridor"] = "cubic-bezier(0.2, 0.0, 0.0, 1.0)",
                ["ease-arrival"] = "cubic-bezier(0.0, 0.0, 0.2, 1.0)",
                ["space-0"] = "0",
                ["space-2"] = "2px",
                ["space-4"] = "4px",
                ["space-8"] = "8px",
                ["space-10"] = "10px",
                ["space-12"] = "12px",
                ["space-16"] = "16px",
                ["space-24"] = "24px",
                ["space-32"] = "32px",
                ["space-40"] = "40px",
                ["space-48"] = "48px",
                ["space-64"] = "64px",
                ["layout-content-max"] = "80rem",
                ["layout-content-wide"] = "96rem",
                ["layout-prose-max"] = "72ch",
                ["rhythm-tight"] = "4px",
                ["rhythm-snug"] = "8px",
                ["rhythm-normal"] = "12px",
                ["rhythm-loose"] = "16px",
                ["rhythm-roomy"] = "24px",
                ["wash-brand-4"] = "rgba(80, 0, 0, 0.04)",
                ["wash-brand-6"] = "rgba(80, 0, 0, 0.06)",
                ["wash-brand-8"] = "rgba(80, 0, 0, 0.08)",
                ["wash-brand-12"] = "rgba(80, 0, 0, 0.12)",
                ["wash-brand-18"] = "rgba(80, 0, 0, 0.18)",
                ["wash-brand-22"] = "rgba(80, 0, 0, 0.22)",
                ["wash-brand-35"] = "rgba(80, 0, 0, 0.35)",
                ["color-maroon-50"] = "#fbf3f6",
                ["color-maroon-100"] = "#f5e0e7",
                ["color-maroon-200"] = "#eab5c3",
                ["color-maroon-300"] = "#db859e",
                ["color-maroon-400"] = "#500000",
                ["color-maroon-500"] = "#500000",
                ["color-maroon-600"] = "#4d001f",
                ["color-maroon-700"] = "#3d0018",
                ["color-maroon-800"] = "#2e0012",
                ["color-maroon-900"] = "#1f000c",
                ["color-maroon-950"] = "#150008",
                ["color-gold-50"] = "#fdf9ee",
                ["color-gold-100"] = "#faf0d2",
                ["color-gold-200"] = "#f4dfa1",
                ["color-gold-300"] = "#ecca6f",
                ["color-gold-400"] = "#e3ba4f",
                ["color-gold-500"] = "#ddac37",
                ["color-gold-600"] = "#b58a23",
                ["color-gold-700"] = "#8a691b",
                ["color-gold-800"] = "#604812",
                ["color-gold-900"] = "#3f300b",
                ["color-gold-950"] = "#271e07",
                ["chart-1"] = "#000000",
                ["chart-2"] = "#500000",
                ["chart-3"] = "#5D5D5D",
                ["chart-4"] = "#8A6915",
                ["chart-5"] = "#4A4A4A",
                ["chart-6"] = "#1F5D66",
                ["chart-7"] = "#6B0000",
                ["chart-8"] = "#2A2A2A",
                ["chart-9"] = "#6E5A7E",
                ["chart-10"] = "#7E7350",
                ["map-seq-maroon-1"] = "#FFFFFF",
                ["map-seq-maroon-2"] = "#C8C8C8",
                ["map-seq-maroon-3"] = "#8A8A8A",
                ["map-seq-maroon-4"] = "#4A4A4A",
                ["map-seq-maroon-5"] = "#000000",
                ["map-seq-slate-1"] = "#FFFFFF",
                ["map-seq-slate-2"] = "#C8C8C8",
                ["map-seq-slate-3"] = "#8A8A8A",
                ["map-seq-slate-4"] = "#4A4A4A",
                ["map-seq-slate-5"] = "#000000",
                ["map-outline"] = "#000000",
                ["map-flow"] = "#000000",
                ["color-brand-primary"] = "#500000",
                ["color-brand-primary-deep"] = "#3A0000",
                ["color-brand-accent"] = "#DCAA37",
                ["color-brand-accent-deep"] = "#B88A21",
                ["color-brand-secondary"] = "#000000",
                ["color-brand-fill"] = "#500000",
                ["color-surface-page"] = "#FFFFFF",
                ["color-surface-raised"] = "#FFFFFF",
                ["color-surface-sunken"] = "#F0F0F0",
                ["color-surface-border"] = "#5D5D5D",
                ["color-surface-border-subtle"] = "#5D5D5D",
                ["color-text-primary"] = "#000000",
                ["color-text-secondary"] = "#221F1F",
                ["color-text-muted"] = "#4D4D4D",
                ["color-text-inverse"] = "#FFFFFF",
                ["color-text-brand"] = "#500000",
                ["color-text-on-brand"] = "#FFFFFF",
            };
    }

}
